// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlxgo/tinker/v1/admin.proto

package tinkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{0}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSummary         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ListNodesResponse) GetNodes() []*NodeSummary {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Load          *NodeLoad              `protobuf:"bytes,4,opt,name=load,proto3" json:"load,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSummary) Reset() {
	*x = NodeSummary{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSummary) ProtoMessage() {}

func (x *NodeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSummary.ProtoReflect.Descriptor instead.
func (*NodeSummary) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSummary) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeSummary) GetLoad() *NodeLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *NodeSummary) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DrainNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{4}
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunSummary          `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListRunsResponse) GetRuns() []*RunSummary {
	if x != nil {
		return x.Runs
	}
	return nil
}

type RunSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Algorithm         string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	State             string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CurrentCheckpoint string                 `protobuf:"bytes,5,opt,name=current_checkpoint,json=currentCheckpoint,proto3" json:"current_checkpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RunSummary) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunSummary) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RunSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunSummary) GetCurrentCheckpoint() string {
	if x != nil {
		return x.CurrentCheckpoint
	}
	return ""
}

type InspectRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRunRequest) Reset() {
	*x = InspectRunRequest{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRunRequest) ProtoMessage() {}

func (x *InspectRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRunRequest.ProtoReflect.Descriptor instead.
func (*InspectRunRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *InspectRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type InspectRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunJson       []byte                 `protobuf:"bytes,1,opt,name=run_json,json=runJson,proto3" json:"run_json,omitempty"`
	EventsJson    [][]byte               `protobuf:"bytes,2,rep,name=events_json,json=eventsJson,proto3" json:"events_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRunResponse) Reset() {
	*x = InspectRunResponse{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRunResponse) ProtoMessage() {}

func (x *InspectRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRunResponse.ProtoReflect.Descriptor instead.
func (*InspectRunResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *InspectRunResponse) GetRunJson() []byte {
	if x != nil {
		return x.RunJson
	}
	return nil
}

func (x *InspectRunResponse) GetEventsJson() [][]byte {
	if x != nil {
		return x.EventsJson
	}
	return nil
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{10}
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactRef         `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListArtifactsResponse) GetArtifacts() []*ArtifactRef {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

var File_mlxgo_tinker_v1_admin_proto protoreflect.FileDescriptor

const file_mlxgo_tinker_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1bmlxgo/tinker/v1/admin.proto\x12\x0fmlxgo.tinker.v1\x1a\x1cmlxgo/tinker/v1/common.proto\x1a!mlxgo/tinker/v1/coordinator.proto\"\x12\n" +
	"\x10ListNodesRequest\"G\n" +
	"\x11ListNodesResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.mlxgo.tinker.v1.NodeSummaryR\x05nodes\"\xfc\x01\n" +
	"\vNodeSummary\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12-\n" +
	"\x04load\x18\x04 \x01(\v2\x19.mlxgo.tinker.v1.NodeLoadR\x04load\x12@\n" +
	"\x06labels\x18\x05 \x03(\v2(.mlxgo.tinker.v1.NodeSummary.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x13\n" +
	"\x11DrainNodeResponse\"\x11\n" +
	"\x0fListRunsRequest\"C\n" +
	"\x10ListRunsResponse\x12/\n" +
	"\x04runs\x18\x01 \x03(\v2\x1b.mlxgo.tinker.v1.RunSummaryR\x04runs\"\x9a\x01\n" +
	"\n" +
	"RunSummary\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12-\n" +
	"\x12current_checkpoint\x18\x05 \x01(\tR\x11currentCheckpoint\"*\n" +
	"\x11InspectRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"P\n" +
	"\x12InspectRunResponse\x12\x19\n" +
	"\brun_json\x18\x01 \x01(\fR\arunJson\x12\x1f\n" +
	"\vevents_json\x18\x02 \x03(\fR\n" +
	"eventsJson\"\x16\n" +
	"\x14ListArtifactsRequest\"S\n" +
	"\x15ListArtifactsResponse\x12:\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1c.mlxgo.tinker.v1.ArtifactRefR\tartifacts2\xbd\x03\n" +
	"\vTinkerAdmin\x12R\n" +
	"\tListNodes\x12!.mlxgo.tinker.v1.ListNodesRequest\x1a\".mlxgo.tinker.v1.ListNodesResponse\x12R\n" +
	"\tDrainNode\x12!.mlxgo.tinker.v1.DrainNodeRequest\x1a\".mlxgo.tinker.v1.DrainNodeResponse\x12O\n" +
	"\bListRuns\x12 .mlxgo.tinker.v1.ListRunsRequest\x1a!.mlxgo.tinker.v1.ListRunsResponse\x12U\n" +
	"\n" +
	"InspectRun\x12\".mlxgo.tinker.v1.InspectRunRequest\x1a#.mlxgo.tinker.v1.InspectRunResponse\x12^\n" +
	"\rListArtifacts\x12%.mlxgo.tinker.v1.ListArtifactsRequest\x1a&.mlxgo.tinker.v1.ListArtifactsResponseB5Z3github.com/tmc/mlx-go/internal/tinkerproto/tinkerv1b\x06proto3"

var (
	file_mlxgo_tinker_v1_admin_proto_rawDescOnce sync.Once
	file_mlxgo_tinker_v1_admin_proto_rawDescData []byte
)

func file_mlxgo_tinker_v1_admin_proto_rawDescGZIP() []byte {
	file_mlxgo_tinker_v1_admin_proto_rawDescOnce.Do(func() {
		file_mlxgo_tinker_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_admin_proto_rawDesc), len(file_mlxgo_tinker_v1_admin_proto_rawDesc)))
	})
	return file_mlxgo_tinker_v1_admin_proto_rawDescData
}

var file_mlxgo_tinker_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_mlxgo_tinker_v1_admin_proto_goTypes = []any{
	(*ListNodesRequest)(nil),      // 0: mlxgo.tinker.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 1: mlxgo.tinker.v1.ListNodesResponse
	(*NodeSummary)(nil),           // 2: mlxgo.tinker.v1.NodeSummary
	(*DrainNodeRequest)(nil),      // 3: mlxgo.tinker.v1.DrainNodeRequest
	(*DrainNodeResponse)(nil),     // 4: mlxgo.tinker.v1.DrainNodeResponse
	(*ListRunsRequest)(nil),       // 5: mlxgo.tinker.v1.ListRunsRequest
	(*ListRunsResponse)(nil),      // 6: mlxgo.tinker.v1.ListRunsResponse
	(*RunSummary)(nil),            // 7: mlxgo.tinker.v1.RunSummary
	(*InspectRunRequest)(nil),     // 8: mlxgo.tinker.v1.InspectRunRequest
	(*InspectRunResponse)(nil),    // 9: mlxgo.tinker.v1.InspectRunResponse
	(*ListArtifactsRequest)(nil),  // 10: mlxgo.tinker.v1.ListArtifactsRequest
	(*ListArtifactsResponse)(nil), // 11: mlxgo.tinker.v1.ListArtifactsResponse
	nil,                           // 12: mlxgo.tinker.v1.NodeSummary.LabelsEntry
	(*NodeLoad)(nil),              // 13: mlxgo.tinker.v1.NodeLoad
	(*ArtifactRef)(nil),           // 14: mlxgo.tinker.v1.ArtifactRef
}
var file_mlxgo_tinker_v1_admin_proto_depIdxs = []int32{
	2,  // 0: mlxgo.tinker.v1.ListNodesResponse.nodes:type_name -> mlxgo.tinker.v1.NodeSummary
	13, // 1: mlxgo.tinker.v1.NodeSummary.load:type_name -> mlxgo.tinker.v1.NodeLoad
	12, // 2: mlxgo.tinker.v1.NodeSummary.labels:type_name -> mlxgo.tinker.v1.NodeSummary.LabelsEntry
	7,  // 3: mlxgo.tinker.v1.ListRunsResponse.runs:type_name -> mlxgo.tinker.v1.RunSummary
	14, // 4: mlxgo.tinker.v1.ListArtifactsResponse.artifacts:type_name -> mlxgo.tinker.v1.ArtifactRef
	0,  // 5: mlxgo.tinker.v1.TinkerAdmin.ListNodes:input_type -> mlxgo.tinker.v1.ListNodesRequest
	3,  // 6: mlxgo.tinker.v1.TinkerAdmin.DrainNode:input_type -> mlxgo.tinker.v1.DrainNodeRequest
	5,  // 7: mlxgo.tinker.v1.TinkerAdmin.ListRuns:input_type -> mlxgo.tinker.v1.ListRunsRequest
	8,  // 8: mlxgo.tinker.v1.TinkerAdmin.InspectRun:input_type -> mlxgo.tinker.v1.InspectRunRequest
	10, // 9: mlxgo.tinker.v1.TinkerAdmin.ListArtifacts:input_type -> mlxgo.tinker.v1.ListArtifactsRequest
	1,  // 10: mlxgo.tinker.v1.TinkerAdmin.ListNodes:output_type -> mlxgo.tinker.v1.ListNodesResponse
	4,  // 11: mlxgo.tinker.v1.TinkerAdmin.DrainNode:output_type -> mlxgo.tinker.v1.DrainNodeResponse
	6,  // 12: mlxgo.tinker.v1.TinkerAdmin.ListRuns:output_type -> mlxgo.tinker.v1.ListRunsResponse
	9,  // 13: mlxgo.tinker.v1.TinkerAdmin.InspectRun:output_type -> mlxgo.tinker.v1.InspectRunResponse
	11, // 14: mlxgo.tinker.v1.TinkerAdmin.ListArtifacts:output_type -> mlxgo.tinker.v1.ListArtifactsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_mlxgo_tinker_v1_admin_proto_init() }
func file_mlxgo_tinker_v1_admin_proto_init() {
	if File_mlxgo_tinker_v1_admin_proto != nil {
		return
	}
	file_mlxgo_tinker_v1_common_proto_init()
	file_mlxgo_tinker_v1_coordinator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_admin_proto_rawDesc), len(file_mlxgo_tinker_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mlxgo_tinker_v1_admin_proto_goTypes,
		DependencyIndexes: file_mlxgo_tinker_v1_admin_proto_depIdxs,
		MessageInfos:      file_mlxgo_tinker_v1_admin_proto_msgTypes,
	}.Build()
	File_mlxgo_tinker_v1_admin_proto = out.File
	file_mlxgo_tinker_v1_admin_proto_goTypes = nil
	file_mlxgo_tinker_v1_admin_proto_depIdxs = nil
}
