// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlxgo/tinker/v1/artifact.proto

package tinkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Storage       string                 `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	RootHash      string                 `protobuf:"bytes,6,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,7,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Files         []*ManifestFile        `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Manifest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *Manifest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Manifest) GetFiles() []*ManifestFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Manifest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ManifestFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	BlobId        string                 `protobuf:"bytes,5,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	Chunks        []*ChunkRef            `protobuf:"bytes,6,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestFile) Reset() {
	*x = ManifestFile{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestFile) ProtoMessage() {}

func (x *ManifestFile) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestFile.ProtoReflect.Descriptor instead.
func (*ManifestFile) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ManifestFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ManifestFile) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ManifestFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ManifestFile) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *ManifestFile) GetChunks() []*ChunkRef {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRef) Reset() {
	*x = ChunkRef{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRef) ProtoMessage() {}

func (x *ChunkRef) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRef.ProtoReflect.Descriptor instead.
func (*ChunkRef) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkRef) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkRef) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type PublishManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishManifestRequest) Reset() {
	*x = PublishManifestRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishManifestRequest) ProtoMessage() {}

func (x *PublishManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishManifestRequest.ProtoReflect.Descriptor instead.
func (*PublishManifestRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *PublishManifestRequest) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *PublishManifestRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type PublishManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishManifestResponse) Reset() {
	*x = PublishManifestResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishManifestResponse) ProtoMessage() {}

func (x *PublishManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishManifestResponse.ProtoReflect.Descriptor instead.
func (*PublishManifestResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *PublishManifestResponse) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

type GetManifestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootHashOrAlias string                 `protobuf:"bytes,1,opt,name=root_hash_or_alias,json=rootHashOrAlias,proto3" json:"root_hash_or_alias,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *GetManifestRequest) GetRootHashOrAlias() string {
	if x != nil {
		return x.RootHashOrAlias
	}
	return ""
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *GetManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type DeleteAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAliasRequest) Reset() {
	*x = DeleteAliasRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAliasRequest) ProtoMessage() {}

func (x *DeleteAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAliasRequest.ProtoReflect.Descriptor instead.
func (*DeleteAliasRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DeleteAliasRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAliasResponse) Reset() {
	*x = DeleteAliasResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAliasResponse) ProtoMessage() {}

func (x *DeleteAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAliasResponse.ProtoReflect.Descriptor instead.
func (*DeleteAliasResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{8}
}

type ReportInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Artifacts     []*ArtifactInventory   `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInventoryRequest) Reset() {
	*x = ReportInventoryRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInventoryRequest) ProtoMessage() {}

func (x *ReportInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInventoryRequest.ProtoReflect.Descriptor instead.
func (*ReportInventoryRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{9}
}

func (x *ReportInventoryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportInventoryRequest) GetArtifacts() []*ArtifactInventory {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ReportInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInventoryResponse) Reset() {
	*x = ReportInventoryResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInventoryResponse) ProtoMessage() {}

func (x *ReportInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInventoryResponse.ProtoReflect.Descriptor instead.
func (*ReportInventoryResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{10}
}

type ApplyRetentionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProtectedRootHashes []string               `protobuf:"bytes,2,rep,name=protected_root_hashes,json=protectedRootHashes,proto3" json:"protected_root_hashes,omitempty"`
	TargetFreeBytes     uint64                 `protobuf:"varint,3,opt,name=target_free_bytes,json=targetFreeBytes,proto3" json:"target_free_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyRetentionRequest) Reset() {
	*x = ApplyRetentionRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRetentionRequest) ProtoMessage() {}

func (x *ApplyRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRetentionRequest.ProtoReflect.Descriptor instead.
func (*ApplyRetentionRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyRetentionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ApplyRetentionRequest) GetProtectedRootHashes() []string {
	if x != nil {
		return x.ProtectedRootHashes
	}
	return nil
}

func (x *ApplyRetentionRequest) GetTargetFreeBytes() uint64 {
	if x != nil {
		return x.TargetFreeBytes
	}
	return 0
}

type ApplyRetentionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeletedRootHashes []string               `protobuf:"bytes,1,rep,name=deleted_root_hashes,json=deletedRootHashes,proto3" json:"deleted_root_hashes,omitempty"`
	BytesDeleted      uint64                 `protobuf:"varint,2,opt,name=bytes_deleted,json=bytesDeleted,proto3" json:"bytes_deleted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplyRetentionResponse) Reset() {
	*x = ApplyRetentionResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRetentionResponse) ProtoMessage() {}

func (x *ApplyRetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRetentionResponse.ProtoReflect.Descriptor instead.
func (*ApplyRetentionResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyRetentionResponse) GetDeletedRootHashes() []string {
	if x != nil {
		return x.DeletedRootHashes
	}
	return nil
}

func (x *ApplyRetentionResponse) GetBytesDeleted() uint64 {
	if x != nil {
		return x.BytesDeleted
	}
	return 0
}

type ListPeersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootHash        string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	PreferredLabels []string               `protobuf:"bytes,2,rep,name=preferred_labels,json=preferredLabels,proto3" json:"preferred_labels,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{13}
}

func (x *ListPeersRequest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ListPeersRequest) GetPreferredLabels() []string {
	if x != nil {
		return x.PreferredLabels
	}
	return nil
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{14}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Transports    []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{15}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfo) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *PeerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SignalMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransferId        string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	SourceNodeId      string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId string                 `protobuf:"bytes,3,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	RootHash          string                 `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Kind              string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload           []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{16}
}

func (x *SignalMessage) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *SignalMessage) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *SignalMessage) GetDestinationNodeId() string {
	if x != nil {
		return x.DestinationNodeId
	}
	return ""
}

func (x *SignalMessage) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *SignalMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SignalMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReportTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RootHash      string                 `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	PeerNodeId    string                 `protobuf:"bytes,3,opt,name=peer_node_id,json=peerNodeId,proto3" json:"peer_node_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Bytes         uint64                 `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransferRequest) Reset() {
	*x = ReportTransferRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransferRequest) ProtoMessage() {}

func (x *ReportTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransferRequest.ProtoReflect.Descriptor instead.
func (*ReportTransferRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{17}
}

func (x *ReportTransferRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportTransferRequest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ReportTransferRequest) GetPeerNodeId() string {
	if x != nil {
		return x.PeerNodeId
	}
	return ""
}

func (x *ReportTransferRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ReportTransferRequest) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ReportTransferRequest) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReportTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransferResponse) Reset() {
	*x = ReportTransferResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransferResponse) ProtoMessage() {}

func (x *ReportTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransferResponse.ProtoReflect.Descriptor instead.
func (*ReportTransferResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{18}
}

type HaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaveRequest) Reset() {
	*x = HaveRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaveRequest) ProtoMessage() {}

func (x *HaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaveRequest.ProtoReflect.Descriptor instead.
func (*HaveRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{19}
}

func (x *HaveRequest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

type HaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHashes   []string               `protobuf:"bytes,1,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaveResponse) Reset() {
	*x = HaveResponse{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaveResponse) ProtoMessage() {}

func (x *HaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaveResponse.ProtoReflect.Descriptor instead.
func (*HaveResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{20}
}

func (x *HaveResponse) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type FetchChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	ChunkHash     string                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	TransferToken string                 `protobuf:"bytes,3,opt,name=transfer_token,json=transferToken,proto3" json:"transfer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChunkRequest) Reset() {
	*x = FetchChunkRequest{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChunkRequest) ProtoMessage() {}

func (x *FetchChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChunkRequest.ProtoReflect.Descriptor instead.
func (*FetchChunkRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{21}
}

func (x *FetchChunkRequest) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *FetchChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *FetchChunkRequest) GetTransferToken() string {
	if x != nil {
		return x.TransferToken
	}
	return ""
}

type ChunkFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	ChunkHash     string                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkFrame) Reset() {
	*x = ChunkFrame{}
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkFrame) ProtoMessage() {}

func (x *ChunkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_artifact_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkFrame.ProtoReflect.Descriptor instead.
func (*ChunkFrame) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP(), []int{22}
}

func (x *ChunkFrame) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ChunkFrame) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *ChunkFrame) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkFrame) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ChunkFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mlxgo_tinker_v1_artifact_proto protoreflect.FileDescriptor

const file_mlxgo_tinker_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"\x1emlxgo/tinker/v1/artifact.proto\x12\x0fmlxgo.tinker.v1\x1a\x1cmlxgo/tinker/v1/common.proto\x1a!mlxgo/tinker/v1/coordinator.proto\"\xe9\x02\n" +
	"\bManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\astorage\x18\x03 \x01(\tR\astorage\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1b\n" +
	"\troot_hash\x18\x06 \x01(\tR\brootHash\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\a \x01(\x03R\tchunkSize\x123\n" +
	"\x05files\x18\b \x03(\v2\x1d.mlxgo.tinker.v1.ManifestFileR\x05files\x12C\n" +
	"\bmetadata\x18\t \x03(\v2'.mlxgo.tinker.v1.Manifest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\fManifestFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x17\n" +
	"\ablob_id\x18\x05 \x01(\tR\x06blobId\x121\n" +
	"\x06chunks\x18\x06 \x03(\v2\x19.mlxgo.tinker.v1.ChunkRefR\x06chunks\"d\n" +
	"\bChunkRef\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"e\n" +
	"\x16PublishManifestRequest\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x19.mlxgo.tinker.v1.ManifestR\bmanifest\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"6\n" +
	"\x17PublishManifestResponse\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\"A\n" +
	"\x12GetManifestRequest\x12+\n" +
	"\x12root_hash_or_alias\x18\x01 \x01(\tR\x0frootHashOrAlias\"L\n" +
	"\x13GetManifestResponse\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x19.mlxgo.tinker.v1.ManifestR\bmanifest\"B\n" +
	"\x12DeleteAliasRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13DeleteAliasResponse\"s\n" +
	"\x16ReportInventoryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12@\n" +
	"\tartifacts\x18\x02 \x03(\v2\".mlxgo.tinker.v1.ArtifactInventoryR\tartifacts\"\x19\n" +
	"\x17ReportInventoryResponse\"\x90\x01\n" +
	"\x15ApplyRetentionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\x15protected_root_hashes\x18\x02 \x03(\tR\x13protectedRootHashes\x12*\n" +
	"\x11target_free_bytes\x18\x03 \x01(\x04R\x0ftargetFreeBytes\"m\n" +
	"\x16ApplyRetentionResponse\x12.\n" +
	"\x13deleted_root_hashes\x18\x01 \x03(\tR\x11deletedRootHashes\x12#\n" +
	"\rbytes_deleted\x18\x02 \x01(\x04R\fbytesDeleted\"Z\n" +
	"\x10ListPeersRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12)\n" +
	"\x10preferred_labels\x18\x02 \x03(\tR\x0fpreferredLabels\"D\n" +
	"\x11ListPeersResponse\x12/\n" +
	"\x05peers\x18\x01 \x03(\v2\x19.mlxgo.tinker.v1.PeerInfoR\x05peers\"\xd7\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\x12=\n" +
	"\x06labels\x18\x04 \x03(\v2%.mlxgo.tinker.v1.PeerInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\rSignalMessage\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x03 \x01(\tR\x11destinationNodeId\x12\x1b\n" +
	"\troot_hash\x18\x04 \x01(\tR\brootHash\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\xcd\x01\n" +
	"\x15ReportTransferRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\tR\brootHash\x12 \n" +
	"\fpeer_node_id\x18\x03 \x01(\tR\n" +
	"peerNodeId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x04R\x05bytes\x120\n" +
	"\x05error\x18\x06 \x01(\v2\x1a.mlxgo.tinker.v1.ErrorInfoR\x05error\"\x18\n" +
	"\x16ReportTransferResponse\"*\n" +
	"\vHaveRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\"1\n" +
	"\fHaveResponse\x12!\n" +
	"\fchunk_hashes\x18\x01 \x03(\tR\vchunkHashes\"v\n" +
	"\x11FetchChunkRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\tR\tchunkHash\x12%\n" +
	"\x0etransfer_token\x18\x03 \x01(\tR\rtransferToken\"\x93\x01\n" +
	"\n" +
	"ChunkFrame\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\tR\tchunkHash\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data2\xfd\x05\n" +
	"\x0fArtifactTracker\x12d\n" +
	"\x0fPublishManifest\x12'.mlxgo.tinker.v1.PublishManifestRequest\x1a(.mlxgo.tinker.v1.PublishManifestResponse\x12X\n" +
	"\vGetManifest\x12#.mlxgo.tinker.v1.GetManifestRequest\x1a$.mlxgo.tinker.v1.GetManifestResponse\x12X\n" +
	"\vDeleteAlias\x12#.mlxgo.tinker.v1.DeleteAliasRequest\x1a$.mlxgo.tinker.v1.DeleteAliasResponse\x12d\n" +
	"\x0fReportInventory\x12'.mlxgo.tinker.v1.ReportInventoryRequest\x1a(.mlxgo.tinker.v1.ReportInventoryResponse\x12a\n" +
	"\x0eApplyRetention\x12&.mlxgo.tinker.v1.ApplyRetentionRequest\x1a'.mlxgo.tinker.v1.ApplyRetentionResponse\x12R\n" +
	"\tListPeers\x12!.mlxgo.tinker.v1.ListPeersRequest\x1a\".mlxgo.tinker.v1.ListPeersResponse\x12P\n" +
	"\n" +
	"SignalPeer\x12\x1e.mlxgo.tinker.v1.SignalMessage\x1a\x1e.mlxgo.tinker.v1.SignalMessage(\x010\x01\x12a\n" +
	"\x0eReportTransfer\x12&.mlxgo.tinker.v1.ReportTransferRequest\x1a'.mlxgo.tinker.v1.ReportTransferResponse2\xa4\x01\n" +
	"\fArtifactPeer\x12C\n" +
	"\x04Have\x12\x1c.mlxgo.tinker.v1.HaveRequest\x1a\x1d.mlxgo.tinker.v1.HaveResponse\x12O\n" +
	"\n" +
	"FetchChunk\x12\".mlxgo.tinker.v1.FetchChunkRequest\x1a\x1b.mlxgo.tinker.v1.ChunkFrame0\x01B5Z3github.com/tmc/mlx-go/internal/tinkerproto/tinkerv1b\x06proto3"

var (
	file_mlxgo_tinker_v1_artifact_proto_rawDescOnce sync.Once
	file_mlxgo_tinker_v1_artifact_proto_rawDescData []byte
)

func file_mlxgo_tinker_v1_artifact_proto_rawDescGZIP() []byte {
	file_mlxgo_tinker_v1_artifact_proto_rawDescOnce.Do(func() {
		file_mlxgo_tinker_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_artifact_proto_rawDesc), len(file_mlxgo_tinker_v1_artifact_proto_rawDesc)))
	})
	return file_mlxgo_tinker_v1_artifact_proto_rawDescData
}

var file_mlxgo_tinker_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_mlxgo_tinker_v1_artifact_proto_goTypes = []any{
	(*Manifest)(nil),                // 0: mlxgo.tinker.v1.Manifest
	(*ManifestFile)(nil),            // 1: mlxgo.tinker.v1.ManifestFile
	(*ChunkRef)(nil),                // 2: mlxgo.tinker.v1.ChunkRef
	(*PublishManifestRequest)(nil),  // 3: mlxgo.tinker.v1.PublishManifestRequest
	(*PublishManifestResponse)(nil), // 4: mlxgo.tinker.v1.PublishManifestResponse
	(*GetManifestRequest)(nil),      // 5: mlxgo.tinker.v1.GetManifestRequest
	(*GetManifestResponse)(nil),     // 6: mlxgo.tinker.v1.GetManifestResponse
	(*DeleteAliasRequest)(nil),      // 7: mlxgo.tinker.v1.DeleteAliasRequest
	(*DeleteAliasResponse)(nil),     // 8: mlxgo.tinker.v1.DeleteAliasResponse
	(*ReportInventoryRequest)(nil),  // 9: mlxgo.tinker.v1.ReportInventoryRequest
	(*ReportInventoryResponse)(nil), // 10: mlxgo.tinker.v1.ReportInventoryResponse
	(*ApplyRetentionRequest)(nil),   // 11: mlxgo.tinker.v1.ApplyRetentionRequest
	(*ApplyRetentionResponse)(nil),  // 12: mlxgo.tinker.v1.ApplyRetentionResponse
	(*ListPeersRequest)(nil),        // 13: mlxgo.tinker.v1.ListPeersRequest
	(*ListPeersResponse)(nil),       // 14: mlxgo.tinker.v1.ListPeersResponse
	(*PeerInfo)(nil),                // 15: mlxgo.tinker.v1.PeerInfo
	(*SignalMessage)(nil),           // 16: mlxgo.tinker.v1.SignalMessage
	(*ReportTransferRequest)(nil),   // 17: mlxgo.tinker.v1.ReportTransferRequest
	(*ReportTransferResponse)(nil),  // 18: mlxgo.tinker.v1.ReportTransferResponse
	(*HaveRequest)(nil),             // 19: mlxgo.tinker.v1.HaveRequest
	(*HaveResponse)(nil),            // 20: mlxgo.tinker.v1.HaveResponse
	(*FetchChunkRequest)(nil),       // 21: mlxgo.tinker.v1.FetchChunkRequest
	(*ChunkFrame)(nil),              // 22: mlxgo.tinker.v1.ChunkFrame
	nil,                             // 23: mlxgo.tinker.v1.Manifest.MetadataEntry
	nil,                             // 24: mlxgo.tinker.v1.PeerInfo.LabelsEntry
	(*ArtifactInventory)(nil),       // 25: mlxgo.tinker.v1.ArtifactInventory
	(*ErrorInfo)(nil),               // 26: mlxgo.tinker.v1.ErrorInfo
}
var file_mlxgo_tinker_v1_artifact_proto_depIdxs = []int32{
	1,  // 0: mlxgo.tinker.v1.Manifest.files:type_name -> mlxgo.tinker.v1.ManifestFile
	23, // 1: mlxgo.tinker.v1.Manifest.metadata:type_name -> mlxgo.tinker.v1.Manifest.MetadataEntry
	2,  // 2: mlxgo.tinker.v1.ManifestFile.chunks:type_name -> mlxgo.tinker.v1.ChunkRef
	0,  // 3: mlxgo.tinker.v1.PublishManifestRequest.manifest:type_name -> mlxgo.tinker.v1.Manifest
	0,  // 4: mlxgo.tinker.v1.GetManifestResponse.manifest:type_name -> mlxgo.tinker.v1.Manifest
	25, // 5: mlxgo.tinker.v1.ReportInventoryRequest.artifacts:type_name -> mlxgo.tinker.v1.ArtifactInventory
	15, // 6: mlxgo.tinker.v1.ListPeersResponse.peers:type_name -> mlxgo.tinker.v1.PeerInfo
	24, // 7: mlxgo.tinker.v1.PeerInfo.labels:type_name -> mlxgo.tinker.v1.PeerInfo.LabelsEntry
	26, // 8: mlxgo.tinker.v1.ReportTransferRequest.error:type_name -> mlxgo.tinker.v1.ErrorInfo
	3,  // 9: mlxgo.tinker.v1.ArtifactTracker.PublishManifest:input_type -> mlxgo.tinker.v1.PublishManifestRequest
	5,  // 10: mlxgo.tinker.v1.ArtifactTracker.GetManifest:input_type -> mlxgo.tinker.v1.GetManifestRequest
	7,  // 11: mlxgo.tinker.v1.ArtifactTracker.DeleteAlias:input_type -> mlxgo.tinker.v1.DeleteAliasRequest
	9,  // 12: mlxgo.tinker.v1.ArtifactTracker.ReportInventory:input_type -> mlxgo.tinker.v1.ReportInventoryRequest
	11, // 13: mlxgo.tinker.v1.ArtifactTracker.ApplyRetention:input_type -> mlxgo.tinker.v1.ApplyRetentionRequest
	13, // 14: mlxgo.tinker.v1.ArtifactTracker.ListPeers:input_type -> mlxgo.tinker.v1.ListPeersRequest
	16, // 15: mlxgo.tinker.v1.ArtifactTracker.SignalPeer:input_type -> mlxgo.tinker.v1.SignalMessage
	17, // 16: mlxgo.tinker.v1.ArtifactTracker.ReportTransfer:input_type -> mlxgo.tinker.v1.ReportTransferRequest
	19, // 17: mlxgo.tinker.v1.ArtifactPeer.Have:input_type -> mlxgo.tinker.v1.HaveRequest
	21, // 18: mlxgo.tinker.v1.ArtifactPeer.FetchChunk:input_type -> mlxgo.tinker.v1.FetchChunkRequest
	4,  // 19: mlxgo.tinker.v1.ArtifactTracker.PublishManifest:output_type -> mlxgo.tinker.v1.PublishManifestResponse
	6,  // 20: mlxgo.tinker.v1.ArtifactTracker.GetManifest:output_type -> mlxgo.tinker.v1.GetManifestResponse
	8,  // 21: mlxgo.tinker.v1.ArtifactTracker.DeleteAlias:output_type -> mlxgo.tinker.v1.DeleteAliasResponse
	10, // 22: mlxgo.tinker.v1.ArtifactTracker.ReportInventory:output_type -> mlxgo.tinker.v1.ReportInventoryResponse
	12, // 23: mlxgo.tinker.v1.ArtifactTracker.ApplyRetention:output_type -> mlxgo.tinker.v1.ApplyRetentionResponse
	14, // 24: mlxgo.tinker.v1.ArtifactTracker.ListPeers:output_type -> mlxgo.tinker.v1.ListPeersResponse
	16, // 25: mlxgo.tinker.v1.ArtifactTracker.SignalPeer:output_type -> mlxgo.tinker.v1.SignalMessage
	18, // 26: mlxgo.tinker.v1.ArtifactTracker.ReportTransfer:output_type -> mlxgo.tinker.v1.ReportTransferResponse
	20, // 27: mlxgo.tinker.v1.ArtifactPeer.Have:output_type -> mlxgo.tinker.v1.HaveResponse
	22, // 28: mlxgo.tinker.v1.ArtifactPeer.FetchChunk:output_type -> mlxgo.tinker.v1.ChunkFrame
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mlxgo_tinker_v1_artifact_proto_init() }
func file_mlxgo_tinker_v1_artifact_proto_init() {
	if File_mlxgo_tinker_v1_artifact_proto != nil {
		return
	}
	file_mlxgo_tinker_v1_common_proto_init()
	file_mlxgo_tinker_v1_coordinator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_artifact_proto_rawDesc), len(file_mlxgo_tinker_v1_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mlxgo_tinker_v1_artifact_proto_goTypes,
		DependencyIndexes: file_mlxgo_tinker_v1_artifact_proto_depIdxs,
		MessageInfos:      file_mlxgo_tinker_v1_artifact_proto_msgTypes,
	}.Build()
	File_mlxgo_tinker_v1_artifact_proto = out.File
	file_mlxgo_tinker_v1_artifact_proto_goTypes = nil
	file_mlxgo_tinker_v1_artifact_proto_depIdxs = nil
}
