// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlxgo/tinker/v1/common.proto

package tinkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Storage       string                 `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ArtifactRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ArtifactRef) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *ArtifactRef) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ModelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	RootHash      string                 `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	TokenizerId   string                 `protobuf:"bytes,3,opt,name=tokenizer_id,json=tokenizerId,proto3" json:"tokenizer_id,omitempty"`
	RepoId        string                 `protobuf:"bytes,4,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	RepoType      string                 `protobuf:"bytes,5,opt,name=repo_type,json=repoType,proto3" json:"repo_type,omitempty"`
	CommitHash    string                 `protobuf:"bytes,6,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRef) Reset() {
	*x = ModelRef{}
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRef) ProtoMessage() {}

func (x *ModelRef) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRef.ProtoReflect.Descriptor instead.
func (*ModelRef) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ModelRef) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelRef) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ModelRef) GetTokenizerId() string {
	if x != nil {
		return x.TokenizerId
	}
	return ""
}

func (x *ModelRef) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ModelRef) GetRepoType() string {
	if x != nil {
		return x.RepoType
	}
	return ""
}

func (x *ModelRef) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type NodeLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLabels) Reset() {
	*x = NodeLabels{}
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLabels) ProtoMessage() {}

func (x *NodeLabels) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLabels.ProtoReflect.Descriptor instead.
func (*NodeLabels) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *NodeLabels) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dtype         string                 `protobuf:"bytes,1,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Shape         []int64                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Raw           []byte                 `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorData) Reset() {
	*x = TensorData{}
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorData) ProtoMessage() {}

func (x *TensorData) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorData.ProtoReflect.Descriptor instead.
func (*TensorData) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *TensorData) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *TensorData) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *TensorData) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type OperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *OperationResult) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperationResult) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *OperationResult) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_mlxgo_tinker_v1_common_proto protoreflect.FileDescriptor

const file_mlxgo_tinker_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cmlxgo/tinker/v1/common.proto\x12\x0fmlxgo.tinker.v1\"n\n" +
	"\vArtifactRef\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\astorage\x18\x03 \x01(\tR\astorage\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\"\xbc\x01\n" +
	"\bModelRef\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\tR\brootHash\x12!\n" +
	"\ftokenizer_id\x18\x03 \x01(\tR\vtokenizerId\x12\x17\n" +
	"\arepo_id\x18\x04 \x01(\tR\x06repoId\x12\x1b\n" +
	"\trepo_type\x18\x05 \x01(\tR\brepoType\x12\x1f\n" +
	"\vcommit_hash\x18\x06 \x01(\tR\n" +
	"commitHash\"\x88\x01\n" +
	"\n" +
	"NodeLabels\x12?\n" +
	"\x06values\x18\x01 \x03(\v2'.mlxgo.tinker.v1.NodeLabels.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.mlxgo.tinker.v1.ErrorInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\n" +
	"TensorData\x12\x14\n" +
	"\x05dtype\x18\x01 \x01(\tR\x05dtype\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x03R\x05shape\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\fR\x03raw\"\x9d\x01\n" +
	"\x0fOperationResult\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\x120\n" +
	"\x05error\x18\x04 \x01(\v2\x1a.mlxgo.tinker.v1.ErrorInfoR\x05errorB5Z3github.com/tmc/mlx-go/internal/tinkerproto/tinkerv1b\x06proto3"

var (
	file_mlxgo_tinker_v1_common_proto_rawDescOnce sync.Once
	file_mlxgo_tinker_v1_common_proto_rawDescData []byte
)

func file_mlxgo_tinker_v1_common_proto_rawDescGZIP() []byte {
	file_mlxgo_tinker_v1_common_proto_rawDescOnce.Do(func() {
		file_mlxgo_tinker_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_common_proto_rawDesc), len(file_mlxgo_tinker_v1_common_proto_rawDesc)))
	})
	return file_mlxgo_tinker_v1_common_proto_rawDescData
}

var file_mlxgo_tinker_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mlxgo_tinker_v1_common_proto_goTypes = []any{
	(*ArtifactRef)(nil),     // 0: mlxgo.tinker.v1.ArtifactRef
	(*ModelRef)(nil),        // 1: mlxgo.tinker.v1.ModelRef
	(*NodeLabels)(nil),      // 2: mlxgo.tinker.v1.NodeLabels
	(*ErrorInfo)(nil),       // 3: mlxgo.tinker.v1.ErrorInfo
	(*TensorData)(nil),      // 4: mlxgo.tinker.v1.TensorData
	(*OperationResult)(nil), // 5: mlxgo.tinker.v1.OperationResult
	nil,                     // 6: mlxgo.tinker.v1.NodeLabels.ValuesEntry
	nil,                     // 7: mlxgo.tinker.v1.ErrorInfo.MetadataEntry
}
var file_mlxgo_tinker_v1_common_proto_depIdxs = []int32{
	6, // 0: mlxgo.tinker.v1.NodeLabels.values:type_name -> mlxgo.tinker.v1.NodeLabels.ValuesEntry
	7, // 1: mlxgo.tinker.v1.ErrorInfo.metadata:type_name -> mlxgo.tinker.v1.ErrorInfo.MetadataEntry
	3, // 2: mlxgo.tinker.v1.OperationResult.error:type_name -> mlxgo.tinker.v1.ErrorInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mlxgo_tinker_v1_common_proto_init() }
func file_mlxgo_tinker_v1_common_proto_init() {
	if File_mlxgo_tinker_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_common_proto_rawDesc), len(file_mlxgo_tinker_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mlxgo_tinker_v1_common_proto_goTypes,
		DependencyIndexes: file_mlxgo_tinker_v1_common_proto_depIdxs,
		MessageInfos:      file_mlxgo_tinker_v1_common_proto_msgTypes,
	}.Build()
	File_mlxgo_tinker_v1_common_proto = out.File
	file_mlxgo_tinker_v1_common_proto_goTypes = nil
	file_mlxgo_tinker_v1_common_proto_depIdxs = nil
}
