// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlxgo/tinker/v1/coordinator.proto

package tinkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	TrustTier     string                 `protobuf:"bytes,5,opt,name=trust_tier,json=trustTier,proto3" json:"trust_tier,omitempty"`
	Capabilities  *NodeCapabilities      `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterNodeRequest) GetTrustTier() string {
	if x != nil {
		return x.TrustTier
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterNodeRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterNodeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorId       string                 `protobuf:"bytes,1,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	AssignedNodeId      string                 `protobuf:"bytes,2,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	LeaseTimeoutMs      int64                  `protobuf:"varint,4,opt,name=lease_timeout_ms,json=leaseTimeoutMs,proto3" json:"lease_timeout_ms,omitempty"`
	Config              map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *RegisterNodeResponse) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *RegisterNodeResponse) GetLeaseTimeoutMs() int64 {
	if x != nil {
		return x.LeaseTimeoutMs
	}
	return 0
}

func (x *RegisterNodeResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UnixNano      int64                  `protobuf:"varint,2,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	Load          *NodeLoad              `protobuf:"bytes,3,opt,name=load,proto3" json:"load,omitempty"`
	Artifacts     []*ArtifactInventory   `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

func (x *HeartbeatRequest) GetLoad() *NodeLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *HeartbeatRequest) GetArtifacts() []*ArtifactInventory {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorId  string                 `protobuf:"bytes,1,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	DrainRequested bool                   `protobuf:"varint,2,opt,name=drain_requested,json=drainRequested,proto3" json:"drain_requested,omitempty"`
	PrewarmRoots   []string               `protobuf:"bytes,3,rep,name=prewarm_roots,json=prewarmRoots,proto3" json:"prewarm_roots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *HeartbeatResponse) GetDrainRequested() bool {
	if x != nil {
		return x.DrainRequested
	}
	return false
}

func (x *HeartbeatResponse) GetPrewarmRoots() []string {
	if x != nil {
		return x.PrewarmRoots
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WatchRequest) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

type NodeCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommandId        string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	LeaseId          string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OperationId      string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Kind             string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	SeqId            int64                  `protobuf:"varint,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	DeadlineUnixNano int64                  `protobuf:"varint,6,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`
	PayloadJson      []byte                 `protobuf:"bytes,7,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Model            *ModelRef              `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	// Types that are valid to be assigned to Directive:
	//
	//	*NodeCommand_Run
	//	*NodeCommand_Drain
	//	*NodeCommand_Revoke
	//	*NodeCommand_AckOperation
	//	*NodeCommand_ArtifactRetention
	//	*NodeCommand_DeleteArtifact
	Directive     isNodeCommand_Directive `protobuf_oneof:"directive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCommand) Reset() {
	*x = NodeCommand{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCommand) ProtoMessage() {}

func (x *NodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCommand.ProtoReflect.Descriptor instead.
func (*NodeCommand) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *NodeCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *NodeCommand) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *NodeCommand) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *NodeCommand) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeCommand) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *NodeCommand) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

func (x *NodeCommand) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *NodeCommand) GetModel() *ModelRef {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *NodeCommand) GetDirective() isNodeCommand_Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

func (x *NodeCommand) GetRun() *RunOperation {
	if x != nil {
		if x, ok := x.Directive.(*NodeCommand_Run); ok {
			return x.Run
		}
	}
	return nil
}

func (x *NodeCommand) GetDrain() *DrainLease {
	if x != nil {
		if x, ok := x.Directive.(*NodeCommand_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *NodeCommand) GetRevoke() *RevokeLease {
	if x != nil {
		if x, ok := x.Directive.(*NodeCommand_Revoke); ok {
			return x.Revoke
		}
	}
	return nil
}

func (x *NodeCommand) GetAckOperation() *AcknowledgeOperation {
	if x != nil {
		if x, ok := x.Directive.(*NodeCommand_AckOperation); ok {
			return x.AckOperation
		}
	}
	return nil
}

func (x *NodeCommand) GetArtifactRetention() *ApplyArtifactRetention {
	if x != nil {
		if x, ok := x.Directive.(*NodeCommand_ArtifactRetention); ok {
			return x.ArtifactRetention
		}
	}
	return nil
}

func (x *NodeCommand) GetDeleteArtifact() *DeleteArtifact {
	if x != nil {
		if x, ok := x.Directive.(*NodeCommand_DeleteArtifact); ok {
			return x.DeleteArtifact
		}
	}
	return nil
}

type isNodeCommand_Directive interface {
	isNodeCommand_Directive()
}

type NodeCommand_Run struct {
	Run *RunOperation `protobuf:"bytes,20,opt,name=run,proto3,oneof"`
}

type NodeCommand_Drain struct {
	Drain *DrainLease `protobuf:"bytes,21,opt,name=drain,proto3,oneof"`
}

type NodeCommand_Revoke struct {
	Revoke *RevokeLease `protobuf:"bytes,22,opt,name=revoke,proto3,oneof"`
}

type NodeCommand_AckOperation struct {
	AckOperation *AcknowledgeOperation `protobuf:"bytes,23,opt,name=ack_operation,json=ackOperation,proto3,oneof"`
}

type NodeCommand_ArtifactRetention struct {
	ArtifactRetention *ApplyArtifactRetention `protobuf:"bytes,24,opt,name=artifact_retention,json=artifactRetention,proto3,oneof"`
}

type NodeCommand_DeleteArtifact struct {
	DeleteArtifact *DeleteArtifact `protobuf:"bytes,25,opt,name=delete_artifact,json=deleteArtifact,proto3,oneof"`
}

func (*NodeCommand_Run) isNodeCommand_Directive() {}

func (*NodeCommand_Drain) isNodeCommand_Directive() {}

func (*NodeCommand_Revoke) isNodeCommand_Directive() {}

func (*NodeCommand_AckOperation) isNodeCommand_Directive() {}

func (*NodeCommand_ArtifactRetention) isNodeCommand_Directive() {}

func (*NodeCommand_DeleteArtifact) isNodeCommand_Directive() {}

type RunOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunOperation) Reset() {
	*x = RunOperation{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOperation) ProtoMessage() {}

func (x *RunOperation) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOperation.ProtoReflect.Descriptor instead.
func (*RunOperation) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

type DrainLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Checkpoint    bool                   `protobuf:"varint,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainLease) Reset() {
	*x = DrainLease{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainLease) ProtoMessage() {}

func (x *DrainLease) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainLease.ProtoReflect.Descriptor instead.
func (*DrainLease) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *DrainLease) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DrainLease) GetCheckpoint() bool {
	if x != nil {
		return x.Checkpoint
	}
	return false
}

type RevokeLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLease) Reset() {
	*x = RevokeLease{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLease) ProtoMessage() {}

func (x *RevokeLease) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLease.ProtoReflect.Descriptor instead.
func (*RevokeLease) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeLease) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AcknowledgeOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationIds  []string               `protobuf:"bytes,1,rep,name=operation_ids,json=operationIds,proto3" json:"operation_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeOperation) Reset() {
	*x = AcknowledgeOperation{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeOperation) ProtoMessage() {}

func (x *AcknowledgeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeOperation.ProtoReflect.Descriptor instead.
func (*AcknowledgeOperation) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *AcknowledgeOperation) GetOperationIds() []string {
	if x != nil {
		return x.OperationIds
	}
	return nil
}

type ApplyArtifactRetention struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtectedRootHashes []string               `protobuf:"bytes,1,rep,name=protected_root_hashes,json=protectedRootHashes,proto3" json:"protected_root_hashes,omitempty"`
	TargetFreeBytes     uint64                 `protobuf:"varint,2,opt,name=target_free_bytes,json=targetFreeBytes,proto3" json:"target_free_bytes,omitempty"`
	Reason              string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyArtifactRetention) Reset() {
	*x = ApplyArtifactRetention{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyArtifactRetention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyArtifactRetention) ProtoMessage() {}

func (x *ApplyArtifactRetention) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyArtifactRetention.ProtoReflect.Descriptor instead.
func (*ApplyArtifactRetention) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyArtifactRetention) GetProtectedRootHashes() []string {
	if x != nil {
		return x.ProtectedRootHashes
	}
	return nil
}

func (x *ApplyArtifactRetention) GetTargetFreeBytes() uint64 {
	if x != nil {
		return x.TargetFreeBytes
	}
	return 0
}

func (x *ApplyArtifactRetention) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHashes    []string               `protobuf:"bytes,1,rep,name=root_hashes,json=rootHashes,proto3" json:"root_hashes,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifact) Reset() {
	*x = DeleteArtifact{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifact) ProtoMessage() {}

func (x *DeleteArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifact.ProtoReflect.Descriptor instead.
func (*DeleteArtifact) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteArtifact) GetRootHashes() []string {
	if x != nil {
		return x.RootHashes
	}
	return nil
}

func (x *DeleteArtifact) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NodeEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeId      string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CommandId   string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	LeaseId     string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OperationId string                 `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Kind        string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	UnixNano    int64                  `protobuf:"varint,6,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeEvent_Ack
	//	*NodeEvent_Started
	//	*NodeEvent_Completed
	//	*NodeEvent_Failed
	//	*NodeEvent_Telemetry
	//	*NodeEvent_Lifecycle
	Payload       isNodeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *NodeEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *NodeEvent) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *NodeEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *NodeEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeEvent) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

func (x *NodeEvent) GetPayload() isNodeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeEvent) GetAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *NodeEvent) GetStarted() *OperationStarted {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *NodeEvent) GetCompleted() *OperationCompleted {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *NodeEvent) GetFailed() *OperationFailed {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *NodeEvent) GetTelemetry() *NodeTelemetry {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *NodeEvent) GetLifecycle() *LifecycleEvent {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Lifecycle); ok {
			return x.Lifecycle
		}
	}
	return nil
}

type isNodeEvent_Payload interface {
	isNodeEvent_Payload()
}

type NodeEvent_Ack struct {
	Ack *CommandAck `protobuf:"bytes,10,opt,name=ack,proto3,oneof"`
}

type NodeEvent_Started struct {
	Started *OperationStarted `protobuf:"bytes,11,opt,name=started,proto3,oneof"`
}

type NodeEvent_Completed struct {
	Completed *OperationCompleted `protobuf:"bytes,12,opt,name=completed,proto3,oneof"`
}

type NodeEvent_Failed struct {
	Failed *OperationFailed `protobuf:"bytes,13,opt,name=failed,proto3,oneof"`
}

type NodeEvent_Telemetry struct {
	Telemetry *NodeTelemetry `protobuf:"bytes,14,opt,name=telemetry,proto3,oneof"`
}

type NodeEvent_Lifecycle struct {
	Lifecycle *LifecycleEvent `protobuf:"bytes,15,opt,name=lifecycle,proto3,oneof"`
}

func (*NodeEvent_Ack) isNodeEvent_Payload() {}

func (*NodeEvent_Started) isNodeEvent_Payload() {}

func (*NodeEvent_Completed) isNodeEvent_Payload() {}

func (*NodeEvent_Failed) isNodeEvent_Payload() {}

func (*NodeEvent_Telemetry) isNodeEvent_Payload() {}

func (*NodeEvent_Lifecycle) isNodeEvent_Payload() {}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{13}
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{14}
}

type OperationStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStarted) Reset() {
	*x = OperationStarted{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStarted) ProtoMessage() {}

func (x *OperationStarted) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStarted.ProtoReflect.Descriptor instead.
func (*OperationStarted) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{15}
}

type OperationCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationCompleted) Reset() {
	*x = OperationCompleted{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCompleted) ProtoMessage() {}

func (x *OperationCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCompleted.ProtoReflect.Descriptor instead.
func (*OperationCompleted) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *OperationCompleted) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type OperationFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorInfo             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationFailed) Reset() {
	*x = OperationFailed{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationFailed) ProtoMessage() {}

func (x *OperationFailed) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationFailed.ProtoReflect.Descriptor instead.
func (*OperationFailed) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{17}
}

func (x *OperationFailed) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type LifecycleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEvent) Reset() {
	*x = LifecycleEvent{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEvent) ProtoMessage() {}

func (x *LifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEvent.ProtoReflect.Descriptor instead.
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{18}
}

func (x *LifecycleEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *LifecycleEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type NodeCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Backends       []*Backend             `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	Memory         *MemoryInfo            `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk           *DiskInfo              `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Models         []*NodeModel           `protobuf:"bytes,4,rep,name=models,proto3" json:"models,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,5,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Features       *NodeFeatures          `protobuf:"bytes,6,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{19}
}

func (x *NodeCapabilities) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *NodeCapabilities) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *NodeCapabilities) GetDisk() *DiskInfo {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *NodeCapabilities) GetModels() []*NodeModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *NodeCapabilities) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *NodeCapabilities) GetFeatures() *NodeFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	UnifiedMemory bool                   `protobuf:"varint,3,opt,name=unified_memory,json=unifiedMemory,proto3" json:"unified_memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{20}
}

func (x *Backend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backend) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Backend) GetUnifiedMemory() bool {
	if x != nil {
		return x.UnifiedMemory
	}
	return false
}

type MemoryInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{21}
}

func (x *MemoryInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryInfo) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type DiskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RootBytes      uint64                 `protobuf:"varint,1,opt,name=root_bytes,json=rootBytes,proto3" json:"root_bytes,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{22}
}

func (x *DiskInfo) GetRootBytes() uint64 {
	if x != nil {
		return x.RootBytes
	}
	return 0
}

func (x *DiskInfo) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type NodeModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RootHash      string                 `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	TokenizerId   string                 `protobuf:"bytes,3,opt,name=tokenizer_id,json=tokenizerId,proto3" json:"tokenizer_id,omitempty"`
	MaxContext    int32                  `protobuf:"varint,4,opt,name=max_context,json=maxContext,proto3" json:"max_context,omitempty"`
	Dtype         string                 `protobuf:"bytes,5,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Quant         string                 `protobuf:"bytes,6,opt,name=quant,proto3" json:"quant,omitempty"`
	CanTrain      bool                   `protobuf:"varint,7,opt,name=can_train,json=canTrain,proto3" json:"can_train,omitempty"`
	CanSample     bool                   `protobuf:"varint,8,opt,name=can_sample,json=canSample,proto3" json:"can_sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeModel) Reset() {
	*x = NodeModel{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeModel) ProtoMessage() {}

func (x *NodeModel) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeModel.ProtoReflect.Descriptor instead.
func (*NodeModel) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{23}
}

func (x *NodeModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeModel) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *NodeModel) GetTokenizerId() string {
	if x != nil {
		return x.TokenizerId
	}
	return ""
}

func (x *NodeModel) GetMaxContext() int32 {
	if x != nil {
		return x.MaxContext
	}
	return 0
}

func (x *NodeModel) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *NodeModel) GetQuant() string {
	if x != nil {
		return x.Quant
	}
	return ""
}

func (x *NodeModel) GetCanTrain() bool {
	if x != nil {
		return x.CanTrain
	}
	return false
}

func (x *NodeModel) GetCanSample() bool {
	if x != nil {
		return x.CanSample
	}
	return false
}

type NodeFeatures struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Lora               bool                   `protobuf:"varint,1,opt,name=lora,proto3" json:"lora,omitempty"`
	OptimizerState     bool                   `protobuf:"varint,2,opt,name=optimizer_state,json=optimizerState,proto3" json:"optimizer_state,omitempty"`
	Sampling           bool                   `protobuf:"varint,3,opt,name=sampling,proto3" json:"sampling,omitempty"`
	TopKPromptLogprobs bool                   `protobuf:"varint,4,opt,name=top_k_prompt_logprobs,json=topKPromptLogprobs,proto3" json:"top_k_prompt_logprobs,omitempty"`
	CustomLossArrays   bool                   `protobuf:"varint,5,opt,name=custom_loss_arrays,json=customLossArrays,proto3" json:"custom_loss_arrays,omitempty"`
	Interpretability   bool                   `protobuf:"varint,6,opt,name=interpretability,proto3" json:"interpretability,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeFeatures) Reset() {
	*x = NodeFeatures{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFeatures) ProtoMessage() {}

func (x *NodeFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFeatures.ProtoReflect.Descriptor instead.
func (*NodeFeatures) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{24}
}

func (x *NodeFeatures) GetLora() bool {
	if x != nil {
		return x.Lora
	}
	return false
}

func (x *NodeFeatures) GetOptimizerState() bool {
	if x != nil {
		return x.OptimizerState
	}
	return false
}

func (x *NodeFeatures) GetSampling() bool {
	if x != nil {
		return x.Sampling
	}
	return false
}

func (x *NodeFeatures) GetTopKPromptLogprobs() bool {
	if x != nil {
		return x.TopKPromptLogprobs
	}
	return false
}

func (x *NodeFeatures) GetCustomLossArrays() bool {
	if x != nil {
		return x.CustomLossArrays
	}
	return false
}

func (x *NodeFeatures) GetInterpretability() bool {
	if x != nil {
		return x.Interpretability
	}
	return false
}

type NodeLoad struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActiveLeases         int32                  `protobuf:"varint,1,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	QueuedOperations     int32                  `protobuf:"varint,2,opt,name=queued_operations,json=queuedOperations,proto3" json:"queued_operations,omitempty"`
	MemoryAvailableBytes uint64                 `protobuf:"varint,3,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	TemperatureCelsius   float64                `protobuf:"fixed64,4,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeLoad) Reset() {
	*x = NodeLoad{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLoad) ProtoMessage() {}

func (x *NodeLoad) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLoad.ProtoReflect.Descriptor instead.
func (*NodeLoad) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{25}
}

func (x *NodeLoad) GetActiveLeases() int32 {
	if x != nil {
		return x.ActiveLeases
	}
	return 0
}

func (x *NodeLoad) GetQueuedOperations() int32 {
	if x != nil {
		return x.QueuedOperations
	}
	return 0
}

func (x *NodeLoad) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *NodeLoad) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

type ArtifactInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	BytesPresent  uint64                 `protobuf:"varint,3,opt,name=bytes_present,json=bytesPresent,proto3" json:"bytes_present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactInventory) Reset() {
	*x = ArtifactInventory{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactInventory) ProtoMessage() {}

func (x *ArtifactInventory) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactInventory.ProtoReflect.Descriptor instead.
func (*ArtifactInventory) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{26}
}

func (x *ArtifactInventory) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ArtifactInventory) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ArtifactInventory) GetBytesPresent() uint64 {
	if x != nil {
		return x.BytesPresent
	}
	return 0
}

type NodeTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       map[string]float64     `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeTelemetry) Reset() {
	*x = NodeTelemetry{}
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTelemetry) ProtoMessage() {}

func (x *NodeTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_coordinator_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTelemetry.ProtoReflect.Descriptor instead.
func (*NodeTelemetry) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP(), []int{27}
}

func (x *NodeTelemetry) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *NodeTelemetry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_mlxgo_tinker_v1_coordinator_proto protoreflect.FileDescriptor

const file_mlxgo_tinker_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"!mlxgo/tinker/v1/coordinator.proto\x12\x0fmlxgo.tinker.v1\x1a\x1cmlxgo/tinker/v1/common.proto\"\xe3\x02\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"trust_tier\x18\x05 \x01(\tR\ttrustTier\x12E\n" +
	"\fcapabilities\x18\x06 \x01(\v2!.mlxgo.tinker.v1.NodeCapabilitiesR\fcapabilities\x12H\n" +
	"\x06labels\x18\a \x03(\v20.mlxgo.tinker.v1.RegisterNodeRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x02\n" +
	"\x14RegisterNodeResponse\x12%\n" +
	"\x0ecoordinator_id\x18\x01 \x01(\tR\rcoordinatorId\x12(\n" +
	"\x10assigned_node_id\x18\x02 \x01(\tR\x0eassignedNodeId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\x03R\x13heartbeatIntervalMs\x12(\n" +
	"\x10lease_timeout_ms\x18\x04 \x01(\x03R\x0eleaseTimeoutMs\x12I\n" +
	"\x06config\x18\x05 \x03(\v21.mlxgo.tinker.v1.RegisterNodeResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tunix_nano\x18\x02 \x01(\x03R\bunixNano\x12-\n" +
	"\x04load\x18\x03 \x01(\v2\x19.mlxgo.tinker.v1.NodeLoadR\x04load\x12@\n" +
	"\tartifacts\x18\x04 \x03(\v2\".mlxgo.tinker.v1.ArtifactInventoryR\tartifacts\"\x88\x01\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0ecoordinator_id\x18\x01 \x01(\tR\rcoordinatorId\x12'\n" +
	"\x0fdrain_requested\x18\x02 \x01(\bR\x0edrainRequested\x12#\n" +
	"\rprewarm_roots\x18\x03 \x03(\tR\fprewarmRoots\"N\n" +
	"\fWatchRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\"\xb8\x05\n" +
	"\vNodeCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x15\n" +
	"\x06seq_id\x18\x05 \x01(\x03R\x05seqId\x12,\n" +
	"\x12deadline_unix_nano\x18\x06 \x01(\x03R\x10deadlineUnixNano\x12!\n" +
	"\fpayload_json\x18\a \x01(\fR\vpayloadJson\x12/\n" +
	"\x05model\x18\b \x01(\v2\x19.mlxgo.tinker.v1.ModelRefR\x05model\x121\n" +
	"\x03run\x18\x14 \x01(\v2\x1d.mlxgo.tinker.v1.RunOperationH\x00R\x03run\x123\n" +
	"\x05drain\x18\x15 \x01(\v2\x1b.mlxgo.tinker.v1.DrainLeaseH\x00R\x05drain\x126\n" +
	"\x06revoke\x18\x16 \x01(\v2\x1c.mlxgo.tinker.v1.RevokeLeaseH\x00R\x06revoke\x12L\n" +
	"\rack_operation\x18\x17 \x01(\v2%.mlxgo.tinker.v1.AcknowledgeOperationH\x00R\fackOperation\x12X\n" +
	"\x12artifact_retention\x18\x18 \x01(\v2'.mlxgo.tinker.v1.ApplyArtifactRetentionH\x00R\x11artifactRetention\x12J\n" +
	"\x0fdelete_artifact\x18\x19 \x01(\v2\x1f.mlxgo.tinker.v1.DeleteArtifactH\x00R\x0edeleteArtifactB\v\n" +
	"\tdirective\"\x0e\n" +
	"\fRunOperation\"D\n" +
	"\n" +
	"DrainLease\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\bR\n" +
	"checkpoint\"%\n" +
	"\vRevokeLease\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\";\n" +
	"\x14AcknowledgeOperation\x12#\n" +
	"\roperation_ids\x18\x01 \x03(\tR\foperationIds\"\x90\x01\n" +
	"\x16ApplyArtifactRetention\x122\n" +
	"\x15protected_root_hashes\x18\x01 \x03(\tR\x13protectedRootHashes\x12*\n" +
	"\x11target_free_bytes\x18\x02 \x01(\x04R\x0ftargetFreeBytes\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"I\n" +
	"\x0eDeleteArtifact\x12\x1f\n" +
	"\vroot_hashes\x18\x01 \x03(\tR\n" +
	"rootHashes\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xaf\x04\n" +
	"\tNodeEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12!\n" +
	"\foperation_id\x18\x04 \x01(\tR\voperationId\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1b\n" +
	"\tunix_nano\x18\x06 \x01(\x03R\bunixNano\x12/\n" +
	"\x03ack\x18\n" +
	" \x01(\v2\x1b.mlxgo.tinker.v1.CommandAckH\x00R\x03ack\x12=\n" +
	"\astarted\x18\v \x01(\v2!.mlxgo.tinker.v1.OperationStartedH\x00R\astarted\x12C\n" +
	"\tcompleted\x18\f \x01(\v2#.mlxgo.tinker.v1.OperationCompletedH\x00R\tcompleted\x12:\n" +
	"\x06failed\x18\r \x01(\v2 .mlxgo.tinker.v1.OperationFailedH\x00R\x06failed\x12>\n" +
	"\ttelemetry\x18\x0e \x01(\v2\x1e.mlxgo.tinker.v1.NodeTelemetryH\x00R\ttelemetry\x12?\n" +
	"\tlifecycle\x18\x0f \x01(\v2\x1f.mlxgo.tinker.v1.LifecycleEventH\x00R\tlifecycleB\t\n" +
	"\apayload\"\x10\n" +
	"\x0eReportResponse\"\f\n" +
	"\n" +
	"CommandAck\"\x12\n" +
	"\x10OperationStarted\"N\n" +
	"\x12OperationCompleted\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .mlxgo.tinker.v1.OperationResultR\x06result\"C\n" +
	"\x0fOperationFailed\x120\n" +
	"\x05error\x18\x01 \x01(\v2\x1a.mlxgo.tinker.v1.ErrorInfoR\x05error\"\xae\x01\n" +
	"\x0eLifecycleEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.mlxgo.tinker.v1.LifecycleEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x02\n" +
	"\x10NodeCapabilities\x124\n" +
	"\bbackends\x18\x01 \x03(\v2\x18.mlxgo.tinker.v1.BackendR\bbackends\x123\n" +
	"\x06memory\x18\x02 \x01(\v2\x1b.mlxgo.tinker.v1.MemoryInfoR\x06memory\x12-\n" +
	"\x04disk\x18\x03 \x01(\v2\x19.mlxgo.tinker.v1.DiskInfoR\x04disk\x122\n" +
	"\x06models\x18\x04 \x03(\v2\x1a.mlxgo.tinker.v1.NodeModelR\x06models\x12'\n" +
	"\x0fmax_concurrency\x18\x05 \x01(\x05R\x0emaxConcurrency\x129\n" +
	"\bfeatures\x18\x06 \x01(\v2\x1d.mlxgo.tinker.v1.NodeFeaturesR\bfeatures\"\\\n" +
	"\aBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12%\n" +
	"\x0eunified_memory\x18\x03 \x01(\bR\runifiedMemory\"V\n" +
	"\n" +
	"MemoryInfo\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\"R\n" +
	"\bDiskInfo\x12\x1d\n" +
	"\n" +
	"root_bytes\x18\x01 \x01(\x04R\trootBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\"\xe8\x01\n" +
	"\tNodeModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\tR\brootHash\x12!\n" +
	"\ftokenizer_id\x18\x03 \x01(\tR\vtokenizerId\x12\x1f\n" +
	"\vmax_context\x18\x04 \x01(\x05R\n" +
	"maxContext\x12\x14\n" +
	"\x05dtype\x18\x05 \x01(\tR\x05dtype\x12\x14\n" +
	"\x05quant\x18\x06 \x01(\tR\x05quant\x12\x1b\n" +
	"\tcan_train\x18\a \x01(\bR\bcanTrain\x12\x1d\n" +
	"\n" +
	"can_sample\x18\b \x01(\bR\tcanSample\"\xf4\x01\n" +
	"\fNodeFeatures\x12\x12\n" +
	"\x04lora\x18\x01 \x01(\bR\x04lora\x12'\n" +
	"\x0foptimizer_state\x18\x02 \x01(\bR\x0eoptimizerState\x12\x1a\n" +
	"\bsampling\x18\x03 \x01(\bR\bsampling\x121\n" +
	"\x15top_k_prompt_logprobs\x18\x04 \x01(\bR\x12topKPromptLogprobs\x12,\n" +
	"\x12custom_loss_arrays\x18\x05 \x01(\bR\x10customLossArrays\x12*\n" +
	"\x10interpretability\x18\x06 \x01(\bR\x10interpretability\"\xc3\x01\n" +
	"\bNodeLoad\x12#\n" +
	"\ractive_leases\x18\x01 \x01(\x05R\factiveLeases\x12+\n" +
	"\x11queued_operations\x18\x02 \x01(\x05R\x10queuedOperations\x124\n" +
	"\x16memory_available_bytes\x18\x03 \x01(\x04R\x14memoryAvailableBytes\x12/\n" +
	"\x13temperature_celsius\x18\x04 \x01(\x01R\x12temperatureCelsius\"k\n" +
	"\x11ArtifactInventory\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12#\n" +
	"\rbytes_present\x18\x03 \x01(\x04R\fbytesPresent\"\x91\x02\n" +
	"\rNodeTelemetry\x12E\n" +
	"\ametrics\x18\x01 \x03(\v2+.mlxgo.tinker.v1.NodeTelemetry.MetricsEntryR\ametrics\x12B\n" +
	"\x06labels\x18\x02 \x03(\v2*.mlxgo.tinker.v1.NodeTelemetry.LabelsEntryR\x06labels\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd5\x02\n" +
	"\x11TinkerCoordinator\x12[\n" +
	"\fRegisterNode\x12$.mlxgo.tinker.v1.RegisterNodeRequest\x1a%.mlxgo.tinker.v1.RegisterNodeResponse\x12R\n" +
	"\tHeartbeat\x12!.mlxgo.tinker.v1.HeartbeatRequest\x1a\".mlxgo.tinker.v1.HeartbeatResponse\x12F\n" +
	"\x05Watch\x12\x1d.mlxgo.tinker.v1.WatchRequest\x1a\x1c.mlxgo.tinker.v1.NodeCommand0\x01\x12G\n" +
	"\x06Report\x12\x1a.mlxgo.tinker.v1.NodeEvent\x1a\x1f.mlxgo.tinker.v1.ReportResponse(\x01B5Z3github.com/tmc/mlx-go/internal/tinkerproto/tinkerv1b\x06proto3"

var (
	file_mlxgo_tinker_v1_coordinator_proto_rawDescOnce sync.Once
	file_mlxgo_tinker_v1_coordinator_proto_rawDescData []byte
)

func file_mlxgo_tinker_v1_coordinator_proto_rawDescGZIP() []byte {
	file_mlxgo_tinker_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_mlxgo_tinker_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_coordinator_proto_rawDesc), len(file_mlxgo_tinker_v1_coordinator_proto_rawDesc)))
	})
	return file_mlxgo_tinker_v1_coordinator_proto_rawDescData
}

var file_mlxgo_tinker_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_mlxgo_tinker_v1_coordinator_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),    // 0: mlxgo.tinker.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 1: mlxgo.tinker.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 2: mlxgo.tinker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 3: mlxgo.tinker.v1.HeartbeatResponse
	(*WatchRequest)(nil),           // 4: mlxgo.tinker.v1.WatchRequest
	(*NodeCommand)(nil),            // 5: mlxgo.tinker.v1.NodeCommand
	(*RunOperation)(nil),           // 6: mlxgo.tinker.v1.RunOperation
	(*DrainLease)(nil),             // 7: mlxgo.tinker.v1.DrainLease
	(*RevokeLease)(nil),            // 8: mlxgo.tinker.v1.RevokeLease
	(*AcknowledgeOperation)(nil),   // 9: mlxgo.tinker.v1.AcknowledgeOperation
	(*ApplyArtifactRetention)(nil), // 10: mlxgo.tinker.v1.ApplyArtifactRetention
	(*DeleteArtifact)(nil),         // 11: mlxgo.tinker.v1.DeleteArtifact
	(*NodeEvent)(nil),              // 12: mlxgo.tinker.v1.NodeEvent
	(*ReportResponse)(nil),         // 13: mlxgo.tinker.v1.ReportResponse
	(*CommandAck)(nil),             // 14: mlxgo.tinker.v1.CommandAck
	(*OperationStarted)(nil),       // 15: mlxgo.tinker.v1.OperationStarted
	(*OperationCompleted)(nil),     // 16: mlxgo.tinker.v1.OperationCompleted
	(*OperationFailed)(nil),        // 17: mlxgo.tinker.v1.OperationFailed
	(*LifecycleEvent)(nil),         // 18: mlxgo.tinker.v1.LifecycleEvent
	(*NodeCapabilities)(nil),       // 19: mlxgo.tinker.v1.NodeCapabilities
	(*Backend)(nil),                // 20: mlxgo.tinker.v1.Backend
	(*MemoryInfo)(nil),             // 21: mlxgo.tinker.v1.MemoryInfo
	(*DiskInfo)(nil),               // 22: mlxgo.tinker.v1.DiskInfo
	(*NodeModel)(nil),              // 23: mlxgo.tinker.v1.NodeModel
	(*NodeFeatures)(nil),           // 24: mlxgo.tinker.v1.NodeFeatures
	(*NodeLoad)(nil),               // 25: mlxgo.tinker.v1.NodeLoad
	(*ArtifactInventory)(nil),      // 26: mlxgo.tinker.v1.ArtifactInventory
	(*NodeTelemetry)(nil),          // 27: mlxgo.tinker.v1.NodeTelemetry
	nil,                            // 28: mlxgo.tinker.v1.RegisterNodeRequest.LabelsEntry
	nil,                            // 29: mlxgo.tinker.v1.RegisterNodeResponse.ConfigEntry
	nil,                            // 30: mlxgo.tinker.v1.LifecycleEvent.MetadataEntry
	nil,                            // 31: mlxgo.tinker.v1.NodeTelemetry.MetricsEntry
	nil,                            // 32: mlxgo.tinker.v1.NodeTelemetry.LabelsEntry
	(*ModelRef)(nil),               // 33: mlxgo.tinker.v1.ModelRef
	(*OperationResult)(nil),        // 34: mlxgo.tinker.v1.OperationResult
	(*ErrorInfo)(nil),              // 35: mlxgo.tinker.v1.ErrorInfo
}
var file_mlxgo_tinker_v1_coordinator_proto_depIdxs = []int32{
	19, // 0: mlxgo.tinker.v1.RegisterNodeRequest.capabilities:type_name -> mlxgo.tinker.v1.NodeCapabilities
	28, // 1: mlxgo.tinker.v1.RegisterNodeRequest.labels:type_name -> mlxgo.tinker.v1.RegisterNodeRequest.LabelsEntry
	29, // 2: mlxgo.tinker.v1.RegisterNodeResponse.config:type_name -> mlxgo.tinker.v1.RegisterNodeResponse.ConfigEntry
	25, // 3: mlxgo.tinker.v1.HeartbeatRequest.load:type_name -> mlxgo.tinker.v1.NodeLoad
	26, // 4: mlxgo.tinker.v1.HeartbeatRequest.artifacts:type_name -> mlxgo.tinker.v1.ArtifactInventory
	33, // 5: mlxgo.tinker.v1.NodeCommand.model:type_name -> mlxgo.tinker.v1.ModelRef
	6,  // 6: mlxgo.tinker.v1.NodeCommand.run:type_name -> mlxgo.tinker.v1.RunOperation
	7,  // 7: mlxgo.tinker.v1.NodeCommand.drain:type_name -> mlxgo.tinker.v1.DrainLease
	8,  // 8: mlxgo.tinker.v1.NodeCommand.revoke:type_name -> mlxgo.tinker.v1.RevokeLease
	9,  // 9: mlxgo.tinker.v1.NodeCommand.ack_operation:type_name -> mlxgo.tinker.v1.AcknowledgeOperation
	10, // 10: mlxgo.tinker.v1.NodeCommand.artifact_retention:type_name -> mlxgo.tinker.v1.ApplyArtifactRetention
	11, // 11: mlxgo.tinker.v1.NodeCommand.delete_artifact:type_name -> mlxgo.tinker.v1.DeleteArtifact
	14, // 12: mlxgo.tinker.v1.NodeEvent.ack:type_name -> mlxgo.tinker.v1.CommandAck
	15, // 13: mlxgo.tinker.v1.NodeEvent.started:type_name -> mlxgo.tinker.v1.OperationStarted
	16, // 14: mlxgo.tinker.v1.NodeEvent.completed:type_name -> mlxgo.tinker.v1.OperationCompleted
	17, // 15: mlxgo.tinker.v1.NodeEvent.failed:type_name -> mlxgo.tinker.v1.OperationFailed
	27, // 16: mlxgo.tinker.v1.NodeEvent.telemetry:type_name -> mlxgo.tinker.v1.NodeTelemetry
	18, // 17: mlxgo.tinker.v1.NodeEvent.lifecycle:type_name -> mlxgo.tinker.v1.LifecycleEvent
	34, // 18: mlxgo.tinker.v1.OperationCompleted.result:type_name -> mlxgo.tinker.v1.OperationResult
	35, // 19: mlxgo.tinker.v1.OperationFailed.error:type_name -> mlxgo.tinker.v1.ErrorInfo
	30, // 20: mlxgo.tinker.v1.LifecycleEvent.metadata:type_name -> mlxgo.tinker.v1.LifecycleEvent.MetadataEntry
	20, // 21: mlxgo.tinker.v1.NodeCapabilities.backends:type_name -> mlxgo.tinker.v1.Backend
	21, // 22: mlxgo.tinker.v1.NodeCapabilities.memory:type_name -> mlxgo.tinker.v1.MemoryInfo
	22, // 23: mlxgo.tinker.v1.NodeCapabilities.disk:type_name -> mlxgo.tinker.v1.DiskInfo
	23, // 24: mlxgo.tinker.v1.NodeCapabilities.models:type_name -> mlxgo.tinker.v1.NodeModel
	24, // 25: mlxgo.tinker.v1.NodeCapabilities.features:type_name -> mlxgo.tinker.v1.NodeFeatures
	31, // 26: mlxgo.tinker.v1.NodeTelemetry.metrics:type_name -> mlxgo.tinker.v1.NodeTelemetry.MetricsEntry
	32, // 27: mlxgo.tinker.v1.NodeTelemetry.labels:type_name -> mlxgo.tinker.v1.NodeTelemetry.LabelsEntry
	0,  // 28: mlxgo.tinker.v1.TinkerCoordinator.RegisterNode:input_type -> mlxgo.tinker.v1.RegisterNodeRequest
	2,  // 29: mlxgo.tinker.v1.TinkerCoordinator.Heartbeat:input_type -> mlxgo.tinker.v1.HeartbeatRequest
	4,  // 30: mlxgo.tinker.v1.TinkerCoordinator.Watch:input_type -> mlxgo.tinker.v1.WatchRequest
	12, // 31: mlxgo.tinker.v1.TinkerCoordinator.Report:input_type -> mlxgo.tinker.v1.NodeEvent
	1,  // 32: mlxgo.tinker.v1.TinkerCoordinator.RegisterNode:output_type -> mlxgo.tinker.v1.RegisterNodeResponse
	3,  // 33: mlxgo.tinker.v1.TinkerCoordinator.Heartbeat:output_type -> mlxgo.tinker.v1.HeartbeatResponse
	5,  // 34: mlxgo.tinker.v1.TinkerCoordinator.Watch:output_type -> mlxgo.tinker.v1.NodeCommand
	13, // 35: mlxgo.tinker.v1.TinkerCoordinator.Report:output_type -> mlxgo.tinker.v1.ReportResponse
	32, // [32:36] is the sub-list for method output_type
	28, // [28:32] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_mlxgo_tinker_v1_coordinator_proto_init() }
func file_mlxgo_tinker_v1_coordinator_proto_init() {
	if File_mlxgo_tinker_v1_coordinator_proto != nil {
		return
	}
	file_mlxgo_tinker_v1_common_proto_init()
	file_mlxgo_tinker_v1_coordinator_proto_msgTypes[5].OneofWrappers = []any{
		(*NodeCommand_Run)(nil),
		(*NodeCommand_Drain)(nil),
		(*NodeCommand_Revoke)(nil),
		(*NodeCommand_AckOperation)(nil),
		(*NodeCommand_ArtifactRetention)(nil),
		(*NodeCommand_DeleteArtifact)(nil),
	}
	file_mlxgo_tinker_v1_coordinator_proto_msgTypes[12].OneofWrappers = []any{
		(*NodeEvent_Ack)(nil),
		(*NodeEvent_Started)(nil),
		(*NodeEvent_Completed)(nil),
		(*NodeEvent_Failed)(nil),
		(*NodeEvent_Telemetry)(nil),
		(*NodeEvent_Lifecycle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_coordinator_proto_rawDesc), len(file_mlxgo_tinker_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mlxgo_tinker_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_mlxgo_tinker_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_mlxgo_tinker_v1_coordinator_proto_msgTypes,
	}.Build()
	File_mlxgo_tinker_v1_coordinator_proto = out.File
	file_mlxgo_tinker_v1_coordinator_proto_goTypes = nil
	file_mlxgo_tinker_v1_coordinator_proto_depIdxs = nil
}
