// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlxgo/tinker/v1/node.proto

package tinkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *CancelRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CancelRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canceled      bool                   `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *CancelResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Checkpoint    bool                   `protobuf:"varint,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *DrainRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DrainRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DrainRequest) GetCheckpoint() bool {
	if x != nil {
		return x.Checkpoint
	}
	return false
}

type DrainResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointPaths []string               `protobuf:"bytes,1,rep,name=checkpoint_paths,json=checkpointPaths,proto3" json:"checkpoint_paths,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *DrainResponse) GetCheckpointPaths() []string {
	if x != nil {
		return x.CheckpointPaths
	}
	return nil
}

type NodeHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealthRequest) Reset() {
	*x = NodeHealthRequest{}
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthRequest) ProtoMessage() {}

func (x *NodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthRequest.ProtoReflect.Descriptor instead.
func (*NodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_node_proto_rawDescGZIP(), []int{4}
}

type NodeHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Load          *NodeLoad              `protobuf:"bytes,3,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealthResponse) Reset() {
	*x = NodeHealthResponse{}
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthResponse) ProtoMessage() {}

func (x *NodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthResponse.ProtoReflect.Descriptor instead.
func (*NodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *NodeHealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHealthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeHealthResponse) GetLoad() *NodeLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

var File_mlxgo_tinker_v1_node_proto protoreflect.FileDescriptor

const file_mlxgo_tinker_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1amlxgo/tinker/v1/node.proto\x12\x0fmlxgo.tinker.v1\x1a\x1cmlxgo/tinker/v1/common.proto\x1a!mlxgo/tinker/v1/coordinator.proto\"M\n" +
	"\rCancelRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\",\n" +
	"\x0eCancelResponse\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\"_\n" +
	"\fDrainRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\bR\n" +
	"checkpoint\":\n" +
	"\rDrainResponse\x12)\n" +
	"\x10checkpoint_paths\x18\x01 \x03(\tR\x0fcheckpointPaths\"\x13\n" +
	"\x11NodeHealthRequest\"r\n" +
	"\x12NodeHealthResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12-\n" +
	"\x04load\x18\x03 \x01(\v2\x19.mlxgo.tinker.v1.NodeLoadR\x04load2\xb9\x02\n" +
	"\n" +
	"TinkerNode\x12E\n" +
	"\x03Run\x12\x1c.mlxgo.tinker.v1.NodeCommand\x1a .mlxgo.tinker.v1.OperationResult\x12I\n" +
	"\x06Cancel\x12\x1e.mlxgo.tinker.v1.CancelRequest\x1a\x1f.mlxgo.tinker.v1.CancelResponse\x12F\n" +
	"\x05Drain\x12\x1d.mlxgo.tinker.v1.DrainRequest\x1a\x1e.mlxgo.tinker.v1.DrainResponse\x12Q\n" +
	"\x06Health\x12\".mlxgo.tinker.v1.NodeHealthRequest\x1a#.mlxgo.tinker.v1.NodeHealthResponseB5Z3github.com/tmc/mlx-go/internal/tinkerproto/tinkerv1b\x06proto3"

var (
	file_mlxgo_tinker_v1_node_proto_rawDescOnce sync.Once
	file_mlxgo_tinker_v1_node_proto_rawDescData []byte
)

func file_mlxgo_tinker_v1_node_proto_rawDescGZIP() []byte {
	file_mlxgo_tinker_v1_node_proto_rawDescOnce.Do(func() {
		file_mlxgo_tinker_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_node_proto_rawDesc), len(file_mlxgo_tinker_v1_node_proto_rawDesc)))
	})
	return file_mlxgo_tinker_v1_node_proto_rawDescData
}

var file_mlxgo_tinker_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mlxgo_tinker_v1_node_proto_goTypes = []any{
	(*CancelRequest)(nil),      // 0: mlxgo.tinker.v1.CancelRequest
	(*CancelResponse)(nil),     // 1: mlxgo.tinker.v1.CancelResponse
	(*DrainRequest)(nil),       // 2: mlxgo.tinker.v1.DrainRequest
	(*DrainResponse)(nil),      // 3: mlxgo.tinker.v1.DrainResponse
	(*NodeHealthRequest)(nil),  // 4: mlxgo.tinker.v1.NodeHealthRequest
	(*NodeHealthResponse)(nil), // 5: mlxgo.tinker.v1.NodeHealthResponse
	(*NodeLoad)(nil),           // 6: mlxgo.tinker.v1.NodeLoad
	(*NodeCommand)(nil),        // 7: mlxgo.tinker.v1.NodeCommand
	(*OperationResult)(nil),    // 8: mlxgo.tinker.v1.OperationResult
}
var file_mlxgo_tinker_v1_node_proto_depIdxs = []int32{
	6, // 0: mlxgo.tinker.v1.NodeHealthResponse.load:type_name -> mlxgo.tinker.v1.NodeLoad
	7, // 1: mlxgo.tinker.v1.TinkerNode.Run:input_type -> mlxgo.tinker.v1.NodeCommand
	0, // 2: mlxgo.tinker.v1.TinkerNode.Cancel:input_type -> mlxgo.tinker.v1.CancelRequest
	2, // 3: mlxgo.tinker.v1.TinkerNode.Drain:input_type -> mlxgo.tinker.v1.DrainRequest
	4, // 4: mlxgo.tinker.v1.TinkerNode.Health:input_type -> mlxgo.tinker.v1.NodeHealthRequest
	8, // 5: mlxgo.tinker.v1.TinkerNode.Run:output_type -> mlxgo.tinker.v1.OperationResult
	1, // 6: mlxgo.tinker.v1.TinkerNode.Cancel:output_type -> mlxgo.tinker.v1.CancelResponse
	3, // 7: mlxgo.tinker.v1.TinkerNode.Drain:output_type -> mlxgo.tinker.v1.DrainResponse
	5, // 8: mlxgo.tinker.v1.TinkerNode.Health:output_type -> mlxgo.tinker.v1.NodeHealthResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mlxgo_tinker_v1_node_proto_init() }
func file_mlxgo_tinker_v1_node_proto_init() {
	if File_mlxgo_tinker_v1_node_proto != nil {
		return
	}
	file_mlxgo_tinker_v1_common_proto_init()
	file_mlxgo_tinker_v1_coordinator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_node_proto_rawDesc), len(file_mlxgo_tinker_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mlxgo_tinker_v1_node_proto_goTypes,
		DependencyIndexes: file_mlxgo_tinker_v1_node_proto_depIdxs,
		MessageInfos:      file_mlxgo_tinker_v1_node_proto_msgTypes,
	}.Build()
	File_mlxgo_tinker_v1_node_proto = out.File
	file_mlxgo_tinker_v1_node_proto_goTypes = nil
	file_mlxgo_tinker_v1_node_proto_depIdxs = nil
}
