// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlxgo/tinker/v1/public.proto

package tinkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DType is the public wire dtype. Integer widths collapse to int64 and bfloat16
// to float32 when decoded into the JSON-equivalent TensorData.
type DType int32

const (
	DType_DTYPE_UNSPECIFIED DType = 0
	DType_DTYPE_FLOAT32     DType = 1
	DType_DTYPE_INT64       DType = 2
	DType_DTYPE_INT32       DType = 3
	DType_DTYPE_BFLOAT16    DType = 4
)

// Enum value maps for DType.
var (
	DType_name = map[int32]string{
		0: "DTYPE_UNSPECIFIED",
		1: "DTYPE_FLOAT32",
		2: "DTYPE_INT64",
		3: "DTYPE_INT32",
		4: "DTYPE_BFLOAT16",
	}
	DType_value = map[string]int32{
		"DTYPE_UNSPECIFIED": 0,
		"DTYPE_FLOAT32":     1,
		"DTYPE_INT64":       2,
		"DTYPE_INT32":       3,
		"DTYPE_BFLOAT16":    4,
	}
)

func (x DType) Enum() *DType {
	p := new(DType)
	*p = x
	return p
}

func (x DType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DType) Descriptor() protoreflect.EnumDescriptor {
	return file_mlxgo_tinker_v1_public_proto_enumTypes[0].Descriptor()
}

func (DType) Type() protoreflect.EnumType {
	return &file_mlxgo_tinker_v1_public_proto_enumTypes[0]
}

func (x DType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DType.Descriptor instead.
func (DType) EnumDescriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{0}
}

// SparseCsr holds a CSR-encoded tensor. values are in the tensor dtype;
// crow_indices and col_indices are int64.
type SparseCsr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []byte                 `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	CrowIndices   []byte                 `protobuf:"bytes,2,opt,name=crow_indices,json=crowIndices,proto3" json:"crow_indices,omitempty"`
	ColIndices    []byte                 `protobuf:"bytes,3,opt,name=col_indices,json=colIndices,proto3" json:"col_indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseCsr) Reset() {
	*x = SparseCsr{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseCsr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseCsr) ProtoMessage() {}

func (x *SparseCsr) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseCsr.ProtoReflect.Descriptor instead.
func (*SparseCsr) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{0}
}

func (x *SparseCsr) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SparseCsr) GetCrowIndices() []byte {
	if x != nil {
		return x.CrowIndices
	}
	return nil
}

func (x *SparseCsr) GetColIndices() []byte {
	if x != nil {
		return x.ColIndices
	}
	return nil
}

// Tensor is one loss_fn_inputs value, either dense bytes or a sparse CSR
// encoding.
type Tensor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Encoding:
	//
	//	*Tensor_Dense
	//	*Tensor_SparseCsr
	Encoding      isTensor_Encoding `protobuf_oneof:"encoding"`
	Dtype         DType             `protobuf:"varint,3,opt,name=dtype,proto3,enum=mlxgo.tinker.v1.DType" json:"dtype,omitempty"`
	Shape         []int64           `protobuf:"varint,4,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{1}
}

func (x *Tensor) GetEncoding() isTensor_Encoding {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *Tensor) GetDense() []byte {
	if x != nil {
		if x, ok := x.Encoding.(*Tensor_Dense); ok {
			return x.Dense
		}
	}
	return nil
}

func (x *Tensor) GetSparseCsr() *SparseCsr {
	if x != nil {
		if x, ok := x.Encoding.(*Tensor_SparseCsr); ok {
			return x.SparseCsr
		}
	}
	return nil
}

func (x *Tensor) GetDtype() DType {
	if x != nil {
		return x.Dtype
	}
	return DType_DTYPE_UNSPECIFIED
}

func (x *Tensor) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type isTensor_Encoding interface {
	isTensor_Encoding()
}

type Tensor_Dense struct {
	Dense []byte `protobuf:"bytes,1,opt,name=dense,proto3,oneof"`
}

type Tensor_SparseCsr struct {
	SparseCsr *SparseCsr `protobuf:"bytes,2,opt,name=sparse_csr,json=sparseCsr,proto3,oneof"`
}

func (*Tensor_Dense) isTensor_Encoding() {}

func (*Tensor_SparseCsr) isTensor_Encoding() {}

// BatchedTensor packs one field across all datums: data is the concatenated
// per-datum bytes, offsets are int64 byte offsets, and trailing_shape is the
// per-element shape after the leading datum dimension.
type BatchedTensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offsets       []byte                 `protobuf:"bytes,2,opt,name=offsets,proto3" json:"offsets,omitempty"`
	Dtype         DType                  `protobuf:"varint,3,opt,name=dtype,proto3,enum=mlxgo.tinker.v1.DType" json:"dtype,omitempty"`
	TrailingShape []int64                `protobuf:"varint,4,rep,packed,name=trailing_shape,json=trailingShape,proto3" json:"trailing_shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedTensor) Reset() {
	*x = BatchedTensor{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedTensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedTensor) ProtoMessage() {}

func (x *BatchedTensor) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedTensor.ProtoReflect.Descriptor instead.
func (*BatchedTensor) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{2}
}

func (x *BatchedTensor) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BatchedTensor) GetOffsets() []byte {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *BatchedTensor) GetDtype() DType {
	if x != nil {
		return x.Dtype
	}
	return DType_DTYPE_UNSPECIFIED
}

func (x *BatchedTensor) GetTrailingShape() []int64 {
	if x != nil {
		return x.TrailingShape
	}
	return nil
}

// ArrayRecord is one structured output field-set. num_datums is authoritative
// for the datum count (it survives server-side field stripping).
type ArrayRecord struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TypeTag       string                    `protobuf:"bytes,1,opt,name=type_tag,json=typeTag,proto3" json:"type_tag,omitempty"`
	Fields        map[string]*BatchedTensor `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NumDatums     int64                     `protobuf:"varint,3,opt,name=num_datums,json=numDatums,proto3" json:"num_datums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayRecord) Reset() {
	*x = ArrayRecord{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayRecord) ProtoMessage() {}

func (x *ArrayRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayRecord.ProtoReflect.Descriptor instead.
func (*ArrayRecord) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayRecord) GetTypeTag() string {
	if x != nil {
		return x.TypeTag
	}
	return ""
}

func (x *ArrayRecord) GetFields() map[string]*BatchedTensor {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ArrayRecord) GetNumDatums() int64 {
	if x != nil {
		return x.NumDatums
	}
	return 0
}

// ForwardBackwardOutput is the proto response shape. localtinker decodes the
// request proto but still replies JSON, so this is defined for completeness and
// the eventual proto response path.
type ForwardBackwardOutput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LossFnOutputType string                 `protobuf:"bytes,1,opt,name=loss_fn_output_type,json=lossFnOutputType,proto3" json:"loss_fn_output_type,omitempty"`
	LossFnOutputs    []*ArrayRecord         `protobuf:"bytes,2,rep,name=loss_fn_outputs,json=lossFnOutputs,proto3" json:"loss_fn_outputs,omitempty"`
	Metrics          map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForwardBackwardOutput) Reset() {
	*x = ForwardBackwardOutput{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardBackwardOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardBackwardOutput) ProtoMessage() {}

func (x *ForwardBackwardOutput) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardBackwardOutput.ProtoReflect.Descriptor instead.
func (*ForwardBackwardOutput) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardBackwardOutput) GetLossFnOutputType() string {
	if x != nil {
		return x.LossFnOutputType
	}
	return ""
}

func (x *ForwardBackwardOutput) GetLossFnOutputs() []*ArrayRecord {
	if x != nil {
		return x.LossFnOutputs
	}
	return nil
}

func (x *ForwardBackwardOutput) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// EncodedTextChunk carries int32 token ids packed as bytes.
type EncodedTextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []byte                 `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedTextChunk) Reset() {
	*x = EncodedTextChunk{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedTextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedTextChunk) ProtoMessage() {}

func (x *EncodedTextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedTextChunk.ProtoReflect.Descriptor instead.
func (*EncodedTextChunk) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{5}
}

func (x *EncodedTextChunk) GetTokens() []byte {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// ImageChunk carries a raw image; the server computes width/height/tokens.
type ImageChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format         string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	ExpectedTokens *int32                 `protobuf:"varint,3,opt,name=expected_tokens,json=expectedTokens,proto3,oneof" json:"expected_tokens,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageChunk) Reset() {
	*x = ImageChunk{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageChunk) ProtoMessage() {}

func (x *ImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageChunk.ProtoReflect.Descriptor instead.
func (*ImageChunk) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{6}
}

func (x *ImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageChunk) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageChunk) GetExpectedTokens() int32 {
	if x != nil && x.ExpectedTokens != nil {
		return *x.ExpectedTokens
	}
	return 0
}

// Chunk is one model_input element.
type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*Chunk_EncodedText
	//	*Chunk_Image
	Chunk         isChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{7}
}

func (x *Chunk) GetChunk() isChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *Chunk) GetEncodedText() *EncodedTextChunk {
	if x != nil {
		if x, ok := x.Chunk.(*Chunk_EncodedText); ok {
			return x.EncodedText
		}
	}
	return nil
}

func (x *Chunk) GetImage() *ImageChunk {
	if x != nil {
		if x, ok := x.Chunk.(*Chunk_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isChunk_Chunk interface {
	isChunk_Chunk()
}

type Chunk_EncodedText struct {
	EncodedText *EncodedTextChunk `protobuf:"bytes,1,opt,name=encoded_text,json=encodedText,proto3,oneof"`
}

type Chunk_Image struct {
	Image *ImageChunk `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*Chunk_EncodedText) isChunk_Chunk() {}

func (*Chunk_Image) isChunk_Chunk() {}

// Datum is one training example: a model input and its loss_fn_inputs tensors.
type Datum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelInput    []*Chunk               `protobuf:"bytes,1,rep,name=model_input,json=modelInput,proto3" json:"model_input,omitempty"`
	LossFnInputs  map[string]*Tensor     `protobuf:"bytes,2,rep,name=loss_fn_inputs,json=lossFnInputs,proto3" json:"loss_fn_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datum) Reset() {
	*x = Datum{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datum) ProtoMessage() {}

func (x *Datum) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datum.ProtoReflect.Descriptor instead.
func (*Datum) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{8}
}

func (x *Datum) GetModelInput() []*Chunk {
	if x != nil {
		return x.ModelInput
	}
	return nil
}

func (x *Datum) GetLossFnInputs() map[string]*Tensor {
	if x != nil {
		return x.LossFnInputs
	}
	return nil
}

// ForwardBackwardRequest is the proto body for POST /api/v1/forward_backward.
// When forward_only is true the server runs the forward pass only.
type ForwardBackwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	SeqId         int32                  `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Data          []*Datum               `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	LossFn        string                 `protobuf:"bytes,4,opt,name=loss_fn,json=lossFn,proto3" json:"loss_fn,omitempty"`
	LossFnConfig  map[string]float64     `protobuf:"bytes,5,rep,name=loss_fn_config,json=lossFnConfig,proto3" json:"loss_fn_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ForwardOnly   bool                   `protobuf:"varint,6,opt,name=forward_only,json=forwardOnly,proto3" json:"forward_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardBackwardRequest) Reset() {
	*x = ForwardBackwardRequest{}
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardBackwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardBackwardRequest) ProtoMessage() {}

func (x *ForwardBackwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlxgo_tinker_v1_public_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardBackwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardBackwardRequest) Descriptor() ([]byte, []int) {
	return file_mlxgo_tinker_v1_public_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardBackwardRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ForwardBackwardRequest) GetSeqId() int32 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *ForwardBackwardRequest) GetData() []*Datum {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ForwardBackwardRequest) GetLossFn() string {
	if x != nil {
		return x.LossFn
	}
	return ""
}

func (x *ForwardBackwardRequest) GetLossFnConfig() map[string]float64 {
	if x != nil {
		return x.LossFnConfig
	}
	return nil
}

func (x *ForwardBackwardRequest) GetForwardOnly() bool {
	if x != nil {
		return x.ForwardOnly
	}
	return false
}

var File_mlxgo_tinker_v1_public_proto protoreflect.FileDescriptor

const file_mlxgo_tinker_v1_public_proto_rawDesc = "" +
	"\n" +
	"\x1cmlxgo/tinker/v1/public.proto\x12\x0fmlxgo.tinker.v1\"g\n" +
	"\tSparseCsr\x12\x16\n" +
	"\x06values\x18\x01 \x01(\fR\x06values\x12!\n" +
	"\fcrow_indices\x18\x02 \x01(\fR\vcrowIndices\x12\x1f\n" +
	"\vcol_indices\x18\x03 \x01(\fR\n" +
	"colIndices\"\xad\x01\n" +
	"\x06Tensor\x12\x16\n" +
	"\x05dense\x18\x01 \x01(\fH\x00R\x05dense\x12;\n" +
	"\n" +
	"sparse_csr\x18\x02 \x01(\v2\x1a.mlxgo.tinker.v1.SparseCsrH\x00R\tsparseCsr\x12,\n" +
	"\x05dtype\x18\x03 \x01(\x0e2\x16.mlxgo.tinker.v1.DTypeR\x05dtype\x12\x14\n" +
	"\x05shape\x18\x04 \x03(\x03R\x05shapeB\n" +
	"\n" +
	"\bencoding\"\x92\x01\n" +
	"\rBatchedTensor\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\aoffsets\x18\x02 \x01(\fR\aoffsets\x12,\n" +
	"\x05dtype\x18\x03 \x01(\x0e2\x16.mlxgo.tinker.v1.DTypeR\x05dtype\x12%\n" +
	"\x0etrailing_shape\x18\x04 \x03(\x03R\rtrailingShape\"\xe4\x01\n" +
	"\vArrayRecord\x12\x19\n" +
	"\btype_tag\x18\x01 \x01(\tR\atypeTag\x12@\n" +
	"\x06fields\x18\x02 \x03(\v2(.mlxgo.tinker.v1.ArrayRecord.FieldsEntryR\x06fields\x12\x1d\n" +
	"\n" +
	"num_datums\x18\x03 \x01(\x03R\tnumDatums\x1aY\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.mlxgo.tinker.v1.BatchedTensorR\x05value:\x028\x01\"\x97\x02\n" +
	"\x15ForwardBackwardOutput\x12-\n" +
	"\x13loss_fn_output_type\x18\x01 \x01(\tR\x10lossFnOutputType\x12D\n" +
	"\x0floss_fn_outputs\x18\x02 \x03(\v2\x1c.mlxgo.tinker.v1.ArrayRecordR\rlossFnOutputs\x12M\n" +
	"\ametrics\x18\x03 \x03(\v23.mlxgo.tinker.v1.ForwardBackwardOutput.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"*\n" +
	"\x10EncodedTextChunk\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\fR\x06tokens\"z\n" +
	"\n" +
	"ImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12,\n" +
	"\x0fexpected_tokens\x18\x03 \x01(\x05H\x00R\x0eexpectedTokens\x88\x01\x01B\x12\n" +
	"\x10_expected_tokens\"\x8d\x01\n" +
	"\x05Chunk\x12F\n" +
	"\fencoded_text\x18\x01 \x01(\v2!.mlxgo.tinker.v1.EncodedTextChunkH\x00R\vencodedText\x123\n" +
	"\x05image\x18\x02 \x01(\v2\x1b.mlxgo.tinker.v1.ImageChunkH\x00R\x05imageB\a\n" +
	"\x05chunk\"\xea\x01\n" +
	"\x05Datum\x127\n" +
	"\vmodel_input\x18\x01 \x03(\v2\x16.mlxgo.tinker.v1.ChunkR\n" +
	"modelInput\x12N\n" +
	"\x0eloss_fn_inputs\x18\x02 \x03(\v2(.mlxgo.tinker.v1.Datum.LossFnInputsEntryR\flossFnInputs\x1aX\n" +
	"\x11LossFnInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.mlxgo.tinker.v1.TensorR\x05value:\x028\x01\"\xd4\x02\n" +
	"\x16ForwardBackwardRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x15\n" +
	"\x06seq_id\x18\x02 \x01(\x05R\x05seqId\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.mlxgo.tinker.v1.DatumR\x04data\x12\x17\n" +
	"\aloss_fn\x18\x04 \x01(\tR\x06lossFn\x12_\n" +
	"\x0eloss_fn_config\x18\x05 \x03(\v29.mlxgo.tinker.v1.ForwardBackwardRequest.LossFnConfigEntryR\flossFnConfig\x12!\n" +
	"\fforward_only\x18\x06 \x01(\bR\vforwardOnly\x1a?\n" +
	"\x11LossFnConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01*g\n" +
	"\x05DType\x12\x15\n" +
	"\x11DTYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDTYPE_FLOAT32\x10\x01\x12\x0f\n" +
	"\vDTYPE_INT64\x10\x02\x12\x0f\n" +
	"\vDTYPE_INT32\x10\x03\x12\x12\n" +
	"\x0eDTYPE_BFLOAT16\x10\x04B5Z3github.com/tmc/mlx-go/internal/tinkerproto/tinkerv1b\x06proto3"

var (
	file_mlxgo_tinker_v1_public_proto_rawDescOnce sync.Once
	file_mlxgo_tinker_v1_public_proto_rawDescData []byte
)

func file_mlxgo_tinker_v1_public_proto_rawDescGZIP() []byte {
	file_mlxgo_tinker_v1_public_proto_rawDescOnce.Do(func() {
		file_mlxgo_tinker_v1_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_public_proto_rawDesc), len(file_mlxgo_tinker_v1_public_proto_rawDesc)))
	})
	return file_mlxgo_tinker_v1_public_proto_rawDescData
}

var file_mlxgo_tinker_v1_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mlxgo_tinker_v1_public_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mlxgo_tinker_v1_public_proto_goTypes = []any{
	(DType)(0),                     // 0: mlxgo.tinker.v1.DType
	(*SparseCsr)(nil),              // 1: mlxgo.tinker.v1.SparseCsr
	(*Tensor)(nil),                 // 2: mlxgo.tinker.v1.Tensor
	(*BatchedTensor)(nil),          // 3: mlxgo.tinker.v1.BatchedTensor
	(*ArrayRecord)(nil),            // 4: mlxgo.tinker.v1.ArrayRecord
	(*ForwardBackwardOutput)(nil),  // 5: mlxgo.tinker.v1.ForwardBackwardOutput
	(*EncodedTextChunk)(nil),       // 6: mlxgo.tinker.v1.EncodedTextChunk
	(*ImageChunk)(nil),             // 7: mlxgo.tinker.v1.ImageChunk
	(*Chunk)(nil),                  // 8: mlxgo.tinker.v1.Chunk
	(*Datum)(nil),                  // 9: mlxgo.tinker.v1.Datum
	(*ForwardBackwardRequest)(nil), // 10: mlxgo.tinker.v1.ForwardBackwardRequest
	nil,                            // 11: mlxgo.tinker.v1.ArrayRecord.FieldsEntry
	nil,                            // 12: mlxgo.tinker.v1.ForwardBackwardOutput.MetricsEntry
	nil,                            // 13: mlxgo.tinker.v1.Datum.LossFnInputsEntry
	nil,                            // 14: mlxgo.tinker.v1.ForwardBackwardRequest.LossFnConfigEntry
}
var file_mlxgo_tinker_v1_public_proto_depIdxs = []int32{
	1,  // 0: mlxgo.tinker.v1.Tensor.sparse_csr:type_name -> mlxgo.tinker.v1.SparseCsr
	0,  // 1: mlxgo.tinker.v1.Tensor.dtype:type_name -> mlxgo.tinker.v1.DType
	0,  // 2: mlxgo.tinker.v1.BatchedTensor.dtype:type_name -> mlxgo.tinker.v1.DType
	11, // 3: mlxgo.tinker.v1.ArrayRecord.fields:type_name -> mlxgo.tinker.v1.ArrayRecord.FieldsEntry
	4,  // 4: mlxgo.tinker.v1.ForwardBackwardOutput.loss_fn_outputs:type_name -> mlxgo.tinker.v1.ArrayRecord
	12, // 5: mlxgo.tinker.v1.ForwardBackwardOutput.metrics:type_name -> mlxgo.tinker.v1.ForwardBackwardOutput.MetricsEntry
	6,  // 6: mlxgo.tinker.v1.Chunk.encoded_text:type_name -> mlxgo.tinker.v1.EncodedTextChunk
	7,  // 7: mlxgo.tinker.v1.Chunk.image:type_name -> mlxgo.tinker.v1.ImageChunk
	8,  // 8: mlxgo.tinker.v1.Datum.model_input:type_name -> mlxgo.tinker.v1.Chunk
	13, // 9: mlxgo.tinker.v1.Datum.loss_fn_inputs:type_name -> mlxgo.tinker.v1.Datum.LossFnInputsEntry
	9,  // 10: mlxgo.tinker.v1.ForwardBackwardRequest.data:type_name -> mlxgo.tinker.v1.Datum
	14, // 11: mlxgo.tinker.v1.ForwardBackwardRequest.loss_fn_config:type_name -> mlxgo.tinker.v1.ForwardBackwardRequest.LossFnConfigEntry
	3,  // 12: mlxgo.tinker.v1.ArrayRecord.FieldsEntry.value:type_name -> mlxgo.tinker.v1.BatchedTensor
	2,  // 13: mlxgo.tinker.v1.Datum.LossFnInputsEntry.value:type_name -> mlxgo.tinker.v1.Tensor
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_mlxgo_tinker_v1_public_proto_init() }
func file_mlxgo_tinker_v1_public_proto_init() {
	if File_mlxgo_tinker_v1_public_proto != nil {
		return
	}
	file_mlxgo_tinker_v1_public_proto_msgTypes[1].OneofWrappers = []any{
		(*Tensor_Dense)(nil),
		(*Tensor_SparseCsr)(nil),
	}
	file_mlxgo_tinker_v1_public_proto_msgTypes[6].OneofWrappers = []any{}
	file_mlxgo_tinker_v1_public_proto_msgTypes[7].OneofWrappers = []any{
		(*Chunk_EncodedText)(nil),
		(*Chunk_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlxgo_tinker_v1_public_proto_rawDesc), len(file_mlxgo_tinker_v1_public_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mlxgo_tinker_v1_public_proto_goTypes,
		DependencyIndexes: file_mlxgo_tinker_v1_public_proto_depIdxs,
		EnumInfos:         file_mlxgo_tinker_v1_public_proto_enumTypes,
		MessageInfos:      file_mlxgo_tinker_v1_public_proto_msgTypes,
	}.Build()
	File_mlxgo_tinker_v1_public_proto = out.File
	file_mlxgo_tinker_v1_public_proto_goTypes = nil
	file_mlxgo_tinker_v1_public_proto_depIdxs = nil
}
