// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mlxgo/tinker/v1/admin.proto

package tinkerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	tinkerv1 "github.com/tmc/localtinker/internal/tinkerproto/tinkerv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TinkerAdminName is the fully-qualified name of the TinkerAdmin service.
	TinkerAdminName = "mlxgo.tinker.v1.TinkerAdmin"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TinkerAdminListNodesProcedure is the fully-qualified name of the TinkerAdmin's ListNodes RPC.
	TinkerAdminListNodesProcedure = "/mlxgo.tinker.v1.TinkerAdmin/ListNodes"
	// TinkerAdminDrainNodeProcedure is the fully-qualified name of the TinkerAdmin's DrainNode RPC.
	TinkerAdminDrainNodeProcedure = "/mlxgo.tinker.v1.TinkerAdmin/DrainNode"
	// TinkerAdminListRunsProcedure is the fully-qualified name of the TinkerAdmin's ListRuns RPC.
	TinkerAdminListRunsProcedure = "/mlxgo.tinker.v1.TinkerAdmin/ListRuns"
	// TinkerAdminInspectRunProcedure is the fully-qualified name of the TinkerAdmin's InspectRun RPC.
	TinkerAdminInspectRunProcedure = "/mlxgo.tinker.v1.TinkerAdmin/InspectRun"
	// TinkerAdminListArtifactsProcedure is the fully-qualified name of the TinkerAdmin's ListArtifacts
	// RPC.
	TinkerAdminListArtifactsProcedure = "/mlxgo.tinker.v1.TinkerAdmin/ListArtifacts"
)

// TinkerAdminClient is a client for the mlxgo.tinker.v1.TinkerAdmin service.
type TinkerAdminClient interface {
	ListNodes(context.Context, *connect.Request[tinkerv1.ListNodesRequest]) (*connect.Response[tinkerv1.ListNodesResponse], error)
	DrainNode(context.Context, *connect.Request[tinkerv1.DrainNodeRequest]) (*connect.Response[tinkerv1.DrainNodeResponse], error)
	ListRuns(context.Context, *connect.Request[tinkerv1.ListRunsRequest]) (*connect.Response[tinkerv1.ListRunsResponse], error)
	InspectRun(context.Context, *connect.Request[tinkerv1.InspectRunRequest]) (*connect.Response[tinkerv1.InspectRunResponse], error)
	ListArtifacts(context.Context, *connect.Request[tinkerv1.ListArtifactsRequest]) (*connect.Response[tinkerv1.ListArtifactsResponse], error)
}

// NewTinkerAdminClient constructs a client for the mlxgo.tinker.v1.TinkerAdmin service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTinkerAdminClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TinkerAdminClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tinkerAdminMethods := tinkerv1.File_mlxgo_tinker_v1_admin_proto.Services().ByName("TinkerAdmin").Methods()
	return &tinkerAdminClient{
		listNodes: connect.NewClient[tinkerv1.ListNodesRequest, tinkerv1.ListNodesResponse](
			httpClient,
			baseURL+TinkerAdminListNodesProcedure,
			connect.WithSchema(tinkerAdminMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
		drainNode: connect.NewClient[tinkerv1.DrainNodeRequest, tinkerv1.DrainNodeResponse](
			httpClient,
			baseURL+TinkerAdminDrainNodeProcedure,
			connect.WithSchema(tinkerAdminMethods.ByName("DrainNode")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[tinkerv1.ListRunsRequest, tinkerv1.ListRunsResponse](
			httpClient,
			baseURL+TinkerAdminListRunsProcedure,
			connect.WithSchema(tinkerAdminMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		inspectRun: connect.NewClient[tinkerv1.InspectRunRequest, tinkerv1.InspectRunResponse](
			httpClient,
			baseURL+TinkerAdminInspectRunProcedure,
			connect.WithSchema(tinkerAdminMethods.ByName("InspectRun")),
			connect.WithClientOptions(opts...),
		),
		listArtifacts: connect.NewClient[tinkerv1.ListArtifactsRequest, tinkerv1.ListArtifactsResponse](
			httpClient,
			baseURL+TinkerAdminListArtifactsProcedure,
			connect.WithSchema(tinkerAdminMethods.ByName("ListArtifacts")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tinkerAdminClient implements TinkerAdminClient.
type tinkerAdminClient struct {
	listNodes     *connect.Client[tinkerv1.ListNodesRequest, tinkerv1.ListNodesResponse]
	drainNode     *connect.Client[tinkerv1.DrainNodeRequest, tinkerv1.DrainNodeResponse]
	listRuns      *connect.Client[tinkerv1.ListRunsRequest, tinkerv1.ListRunsResponse]
	inspectRun    *connect.Client[tinkerv1.InspectRunRequest, tinkerv1.InspectRunResponse]
	listArtifacts *connect.Client[tinkerv1.ListArtifactsRequest, tinkerv1.ListArtifactsResponse]
}

// ListNodes calls mlxgo.tinker.v1.TinkerAdmin.ListNodes.
func (c *tinkerAdminClient) ListNodes(ctx context.Context, req *connect.Request[tinkerv1.ListNodesRequest]) (*connect.Response[tinkerv1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// DrainNode calls mlxgo.tinker.v1.TinkerAdmin.DrainNode.
func (c *tinkerAdminClient) DrainNode(ctx context.Context, req *connect.Request[tinkerv1.DrainNodeRequest]) (*connect.Response[tinkerv1.DrainNodeResponse], error) {
	return c.drainNode.CallUnary(ctx, req)
}

// ListRuns calls mlxgo.tinker.v1.TinkerAdmin.ListRuns.
func (c *tinkerAdminClient) ListRuns(ctx context.Context, req *connect.Request[tinkerv1.ListRunsRequest]) (*connect.Response[tinkerv1.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// InspectRun calls mlxgo.tinker.v1.TinkerAdmin.InspectRun.
func (c *tinkerAdminClient) InspectRun(ctx context.Context, req *connect.Request[tinkerv1.InspectRunRequest]) (*connect.Response[tinkerv1.InspectRunResponse], error) {
	return c.inspectRun.CallUnary(ctx, req)
}

// ListArtifacts calls mlxgo.tinker.v1.TinkerAdmin.ListArtifacts.
func (c *tinkerAdminClient) ListArtifacts(ctx context.Context, req *connect.Request[tinkerv1.ListArtifactsRequest]) (*connect.Response[tinkerv1.ListArtifactsResponse], error) {
	return c.listArtifacts.CallUnary(ctx, req)
}

// TinkerAdminHandler is an implementation of the mlxgo.tinker.v1.TinkerAdmin service.
type TinkerAdminHandler interface {
	ListNodes(context.Context, *connect.Request[tinkerv1.ListNodesRequest]) (*connect.Response[tinkerv1.ListNodesResponse], error)
	DrainNode(context.Context, *connect.Request[tinkerv1.DrainNodeRequest]) (*connect.Response[tinkerv1.DrainNodeResponse], error)
	ListRuns(context.Context, *connect.Request[tinkerv1.ListRunsRequest]) (*connect.Response[tinkerv1.ListRunsResponse], error)
	InspectRun(context.Context, *connect.Request[tinkerv1.InspectRunRequest]) (*connect.Response[tinkerv1.InspectRunResponse], error)
	ListArtifacts(context.Context, *connect.Request[tinkerv1.ListArtifactsRequest]) (*connect.Response[tinkerv1.ListArtifactsResponse], error)
}

// NewTinkerAdminHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTinkerAdminHandler(svc TinkerAdminHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tinkerAdminMethods := tinkerv1.File_mlxgo_tinker_v1_admin_proto.Services().ByName("TinkerAdmin").Methods()
	tinkerAdminListNodesHandler := connect.NewUnaryHandler(
		TinkerAdminListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(tinkerAdminMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerAdminDrainNodeHandler := connect.NewUnaryHandler(
		TinkerAdminDrainNodeProcedure,
		svc.DrainNode,
		connect.WithSchema(tinkerAdminMethods.ByName("DrainNode")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerAdminListRunsHandler := connect.NewUnaryHandler(
		TinkerAdminListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(tinkerAdminMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerAdminInspectRunHandler := connect.NewUnaryHandler(
		TinkerAdminInspectRunProcedure,
		svc.InspectRun,
		connect.WithSchema(tinkerAdminMethods.ByName("InspectRun")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerAdminListArtifactsHandler := connect.NewUnaryHandler(
		TinkerAdminListArtifactsProcedure,
		svc.ListArtifacts,
		connect.WithSchema(tinkerAdminMethods.ByName("ListArtifacts")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mlxgo.tinker.v1.TinkerAdmin/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TinkerAdminListNodesProcedure:
			tinkerAdminListNodesHandler.ServeHTTP(w, r)
		case TinkerAdminDrainNodeProcedure:
			tinkerAdminDrainNodeHandler.ServeHTTP(w, r)
		case TinkerAdminListRunsProcedure:
			tinkerAdminListRunsHandler.ServeHTTP(w, r)
		case TinkerAdminInspectRunProcedure:
			tinkerAdminInspectRunHandler.ServeHTTP(w, r)
		case TinkerAdminListArtifactsProcedure:
			tinkerAdminListArtifactsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTinkerAdminHandler returns CodeUnimplemented from all methods.
type UnimplementedTinkerAdminHandler struct{}

func (UnimplementedTinkerAdminHandler) ListNodes(context.Context, *connect.Request[tinkerv1.ListNodesRequest]) (*connect.Response[tinkerv1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerAdmin.ListNodes is not implemented"))
}

func (UnimplementedTinkerAdminHandler) DrainNode(context.Context, *connect.Request[tinkerv1.DrainNodeRequest]) (*connect.Response[tinkerv1.DrainNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerAdmin.DrainNode is not implemented"))
}

func (UnimplementedTinkerAdminHandler) ListRuns(context.Context, *connect.Request[tinkerv1.ListRunsRequest]) (*connect.Response[tinkerv1.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerAdmin.ListRuns is not implemented"))
}

func (UnimplementedTinkerAdminHandler) InspectRun(context.Context, *connect.Request[tinkerv1.InspectRunRequest]) (*connect.Response[tinkerv1.InspectRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerAdmin.InspectRun is not implemented"))
}

func (UnimplementedTinkerAdminHandler) ListArtifacts(context.Context, *connect.Request[tinkerv1.ListArtifactsRequest]) (*connect.Response[tinkerv1.ListArtifactsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerAdmin.ListArtifacts is not implemented"))
}
