// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mlxgo/tinker/v1/artifact.proto

package tinkerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	tinkerv1 "github.com/tmc/localtinker/internal/tinkerproto/tinkerv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtifactTrackerName is the fully-qualified name of the ArtifactTracker service.
	ArtifactTrackerName = "mlxgo.tinker.v1.ArtifactTracker"
	// ArtifactPeerName is the fully-qualified name of the ArtifactPeer service.
	ArtifactPeerName = "mlxgo.tinker.v1.ArtifactPeer"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtifactTrackerPublishManifestProcedure is the fully-qualified name of the ArtifactTracker's
	// PublishManifest RPC.
	ArtifactTrackerPublishManifestProcedure = "/mlxgo.tinker.v1.ArtifactTracker/PublishManifest"
	// ArtifactTrackerGetManifestProcedure is the fully-qualified name of the ArtifactTracker's
	// GetManifest RPC.
	ArtifactTrackerGetManifestProcedure = "/mlxgo.tinker.v1.ArtifactTracker/GetManifest"
	// ArtifactTrackerDeleteAliasProcedure is the fully-qualified name of the ArtifactTracker's
	// DeleteAlias RPC.
	ArtifactTrackerDeleteAliasProcedure = "/mlxgo.tinker.v1.ArtifactTracker/DeleteAlias"
	// ArtifactTrackerReportInventoryProcedure is the fully-qualified name of the ArtifactTracker's
	// ReportInventory RPC.
	ArtifactTrackerReportInventoryProcedure = "/mlxgo.tinker.v1.ArtifactTracker/ReportInventory"
	// ArtifactTrackerApplyRetentionProcedure is the fully-qualified name of the ArtifactTracker's
	// ApplyRetention RPC.
	ArtifactTrackerApplyRetentionProcedure = "/mlxgo.tinker.v1.ArtifactTracker/ApplyRetention"
	// ArtifactTrackerListPeersProcedure is the fully-qualified name of the ArtifactTracker's ListPeers
	// RPC.
	ArtifactTrackerListPeersProcedure = "/mlxgo.tinker.v1.ArtifactTracker/ListPeers"
	// ArtifactTrackerSignalPeerProcedure is the fully-qualified name of the ArtifactTracker's
	// SignalPeer RPC.
	ArtifactTrackerSignalPeerProcedure = "/mlxgo.tinker.v1.ArtifactTracker/SignalPeer"
	// ArtifactTrackerReportTransferProcedure is the fully-qualified name of the ArtifactTracker's
	// ReportTransfer RPC.
	ArtifactTrackerReportTransferProcedure = "/mlxgo.tinker.v1.ArtifactTracker/ReportTransfer"
	// ArtifactPeerHaveProcedure is the fully-qualified name of the ArtifactPeer's Have RPC.
	ArtifactPeerHaveProcedure = "/mlxgo.tinker.v1.ArtifactPeer/Have"
	// ArtifactPeerFetchChunkProcedure is the fully-qualified name of the ArtifactPeer's FetchChunk RPC.
	ArtifactPeerFetchChunkProcedure = "/mlxgo.tinker.v1.ArtifactPeer/FetchChunk"
)

// ArtifactTrackerClient is a client for the mlxgo.tinker.v1.ArtifactTracker service.
type ArtifactTrackerClient interface {
	PublishManifest(context.Context, *connect.Request[tinkerv1.PublishManifestRequest]) (*connect.Response[tinkerv1.PublishManifestResponse], error)
	GetManifest(context.Context, *connect.Request[tinkerv1.GetManifestRequest]) (*connect.Response[tinkerv1.GetManifestResponse], error)
	DeleteAlias(context.Context, *connect.Request[tinkerv1.DeleteAliasRequest]) (*connect.Response[tinkerv1.DeleteAliasResponse], error)
	ReportInventory(context.Context, *connect.Request[tinkerv1.ReportInventoryRequest]) (*connect.Response[tinkerv1.ReportInventoryResponse], error)
	ApplyRetention(context.Context, *connect.Request[tinkerv1.ApplyRetentionRequest]) (*connect.Response[tinkerv1.ApplyRetentionResponse], error)
	ListPeers(context.Context, *connect.Request[tinkerv1.ListPeersRequest]) (*connect.Response[tinkerv1.ListPeersResponse], error)
	SignalPeer(context.Context) *connect.BidiStreamForClient[tinkerv1.SignalMessage, tinkerv1.SignalMessage]
	ReportTransfer(context.Context, *connect.Request[tinkerv1.ReportTransferRequest]) (*connect.Response[tinkerv1.ReportTransferResponse], error)
}

// NewArtifactTrackerClient constructs a client for the mlxgo.tinker.v1.ArtifactTracker service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactTrackerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactTrackerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactTrackerMethods := tinkerv1.File_mlxgo_tinker_v1_artifact_proto.Services().ByName("ArtifactTracker").Methods()
	return &artifactTrackerClient{
		publishManifest: connect.NewClient[tinkerv1.PublishManifestRequest, tinkerv1.PublishManifestResponse](
			httpClient,
			baseURL+ArtifactTrackerPublishManifestProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("PublishManifest")),
			connect.WithClientOptions(opts...),
		),
		getManifest: connect.NewClient[tinkerv1.GetManifestRequest, tinkerv1.GetManifestResponse](
			httpClient,
			baseURL+ArtifactTrackerGetManifestProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("GetManifest")),
			connect.WithClientOptions(opts...),
		),
		deleteAlias: connect.NewClient[tinkerv1.DeleteAliasRequest, tinkerv1.DeleteAliasResponse](
			httpClient,
			baseURL+ArtifactTrackerDeleteAliasProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("DeleteAlias")),
			connect.WithClientOptions(opts...),
		),
		reportInventory: connect.NewClient[tinkerv1.ReportInventoryRequest, tinkerv1.ReportInventoryResponse](
			httpClient,
			baseURL+ArtifactTrackerReportInventoryProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("ReportInventory")),
			connect.WithClientOptions(opts...),
		),
		applyRetention: connect.NewClient[tinkerv1.ApplyRetentionRequest, tinkerv1.ApplyRetentionResponse](
			httpClient,
			baseURL+ArtifactTrackerApplyRetentionProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("ApplyRetention")),
			connect.WithClientOptions(opts...),
		),
		listPeers: connect.NewClient[tinkerv1.ListPeersRequest, tinkerv1.ListPeersResponse](
			httpClient,
			baseURL+ArtifactTrackerListPeersProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("ListPeers")),
			connect.WithClientOptions(opts...),
		),
		signalPeer: connect.NewClient[tinkerv1.SignalMessage, tinkerv1.SignalMessage](
			httpClient,
			baseURL+ArtifactTrackerSignalPeerProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("SignalPeer")),
			connect.WithClientOptions(opts...),
		),
		reportTransfer: connect.NewClient[tinkerv1.ReportTransferRequest, tinkerv1.ReportTransferResponse](
			httpClient,
			baseURL+ArtifactTrackerReportTransferProcedure,
			connect.WithSchema(artifactTrackerMethods.ByName("ReportTransfer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactTrackerClient implements ArtifactTrackerClient.
type artifactTrackerClient struct {
	publishManifest *connect.Client[tinkerv1.PublishManifestRequest, tinkerv1.PublishManifestResponse]
	getManifest     *connect.Client[tinkerv1.GetManifestRequest, tinkerv1.GetManifestResponse]
	deleteAlias     *connect.Client[tinkerv1.DeleteAliasRequest, tinkerv1.DeleteAliasResponse]
	reportInventory *connect.Client[tinkerv1.ReportInventoryRequest, tinkerv1.ReportInventoryResponse]
	applyRetention  *connect.Client[tinkerv1.ApplyRetentionRequest, tinkerv1.ApplyRetentionResponse]
	listPeers       *connect.Client[tinkerv1.ListPeersRequest, tinkerv1.ListPeersResponse]
	signalPeer      *connect.Client[tinkerv1.SignalMessage, tinkerv1.SignalMessage]
	reportTransfer  *connect.Client[tinkerv1.ReportTransferRequest, tinkerv1.ReportTransferResponse]
}

// PublishManifest calls mlxgo.tinker.v1.ArtifactTracker.PublishManifest.
func (c *artifactTrackerClient) PublishManifest(ctx context.Context, req *connect.Request[tinkerv1.PublishManifestRequest]) (*connect.Response[tinkerv1.PublishManifestResponse], error) {
	return c.publishManifest.CallUnary(ctx, req)
}

// GetManifest calls mlxgo.tinker.v1.ArtifactTracker.GetManifest.
func (c *artifactTrackerClient) GetManifest(ctx context.Context, req *connect.Request[tinkerv1.GetManifestRequest]) (*connect.Response[tinkerv1.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// DeleteAlias calls mlxgo.tinker.v1.ArtifactTracker.DeleteAlias.
func (c *artifactTrackerClient) DeleteAlias(ctx context.Context, req *connect.Request[tinkerv1.DeleteAliasRequest]) (*connect.Response[tinkerv1.DeleteAliasResponse], error) {
	return c.deleteAlias.CallUnary(ctx, req)
}

// ReportInventory calls mlxgo.tinker.v1.ArtifactTracker.ReportInventory.
func (c *artifactTrackerClient) ReportInventory(ctx context.Context, req *connect.Request[tinkerv1.ReportInventoryRequest]) (*connect.Response[tinkerv1.ReportInventoryResponse], error) {
	return c.reportInventory.CallUnary(ctx, req)
}

// ApplyRetention calls mlxgo.tinker.v1.ArtifactTracker.ApplyRetention.
func (c *artifactTrackerClient) ApplyRetention(ctx context.Context, req *connect.Request[tinkerv1.ApplyRetentionRequest]) (*connect.Response[tinkerv1.ApplyRetentionResponse], error) {
	return c.applyRetention.CallUnary(ctx, req)
}

// ListPeers calls mlxgo.tinker.v1.ArtifactTracker.ListPeers.
func (c *artifactTrackerClient) ListPeers(ctx context.Context, req *connect.Request[tinkerv1.ListPeersRequest]) (*connect.Response[tinkerv1.ListPeersResponse], error) {
	return c.listPeers.CallUnary(ctx, req)
}

// SignalPeer calls mlxgo.tinker.v1.ArtifactTracker.SignalPeer.
func (c *artifactTrackerClient) SignalPeer(ctx context.Context) *connect.BidiStreamForClient[tinkerv1.SignalMessage, tinkerv1.SignalMessage] {
	return c.signalPeer.CallBidiStream(ctx)
}

// ReportTransfer calls mlxgo.tinker.v1.ArtifactTracker.ReportTransfer.
func (c *artifactTrackerClient) ReportTransfer(ctx context.Context, req *connect.Request[tinkerv1.ReportTransferRequest]) (*connect.Response[tinkerv1.ReportTransferResponse], error) {
	return c.reportTransfer.CallUnary(ctx, req)
}

// ArtifactTrackerHandler is an implementation of the mlxgo.tinker.v1.ArtifactTracker service.
type ArtifactTrackerHandler interface {
	PublishManifest(context.Context, *connect.Request[tinkerv1.PublishManifestRequest]) (*connect.Response[tinkerv1.PublishManifestResponse], error)
	GetManifest(context.Context, *connect.Request[tinkerv1.GetManifestRequest]) (*connect.Response[tinkerv1.GetManifestResponse], error)
	DeleteAlias(context.Context, *connect.Request[tinkerv1.DeleteAliasRequest]) (*connect.Response[tinkerv1.DeleteAliasResponse], error)
	ReportInventory(context.Context, *connect.Request[tinkerv1.ReportInventoryRequest]) (*connect.Response[tinkerv1.ReportInventoryResponse], error)
	ApplyRetention(context.Context, *connect.Request[tinkerv1.ApplyRetentionRequest]) (*connect.Response[tinkerv1.ApplyRetentionResponse], error)
	ListPeers(context.Context, *connect.Request[tinkerv1.ListPeersRequest]) (*connect.Response[tinkerv1.ListPeersResponse], error)
	SignalPeer(context.Context, *connect.BidiStream[tinkerv1.SignalMessage, tinkerv1.SignalMessage]) error
	ReportTransfer(context.Context, *connect.Request[tinkerv1.ReportTransferRequest]) (*connect.Response[tinkerv1.ReportTransferResponse], error)
}

// NewArtifactTrackerHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactTrackerHandler(svc ArtifactTrackerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactTrackerMethods := tinkerv1.File_mlxgo_tinker_v1_artifact_proto.Services().ByName("ArtifactTracker").Methods()
	artifactTrackerPublishManifestHandler := connect.NewUnaryHandler(
		ArtifactTrackerPublishManifestProcedure,
		svc.PublishManifest,
		connect.WithSchema(artifactTrackerMethods.ByName("PublishManifest")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerGetManifestHandler := connect.NewUnaryHandler(
		ArtifactTrackerGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(artifactTrackerMethods.ByName("GetManifest")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerDeleteAliasHandler := connect.NewUnaryHandler(
		ArtifactTrackerDeleteAliasProcedure,
		svc.DeleteAlias,
		connect.WithSchema(artifactTrackerMethods.ByName("DeleteAlias")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerReportInventoryHandler := connect.NewUnaryHandler(
		ArtifactTrackerReportInventoryProcedure,
		svc.ReportInventory,
		connect.WithSchema(artifactTrackerMethods.ByName("ReportInventory")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerApplyRetentionHandler := connect.NewUnaryHandler(
		ArtifactTrackerApplyRetentionProcedure,
		svc.ApplyRetention,
		connect.WithSchema(artifactTrackerMethods.ByName("ApplyRetention")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerListPeersHandler := connect.NewUnaryHandler(
		ArtifactTrackerListPeersProcedure,
		svc.ListPeers,
		connect.WithSchema(artifactTrackerMethods.ByName("ListPeers")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerSignalPeerHandler := connect.NewBidiStreamHandler(
		ArtifactTrackerSignalPeerProcedure,
		svc.SignalPeer,
		connect.WithSchema(artifactTrackerMethods.ByName("SignalPeer")),
		connect.WithHandlerOptions(opts...),
	)
	artifactTrackerReportTransferHandler := connect.NewUnaryHandler(
		ArtifactTrackerReportTransferProcedure,
		svc.ReportTransfer,
		connect.WithSchema(artifactTrackerMethods.ByName("ReportTransfer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mlxgo.tinker.v1.ArtifactTracker/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactTrackerPublishManifestProcedure:
			artifactTrackerPublishManifestHandler.ServeHTTP(w, r)
		case ArtifactTrackerGetManifestProcedure:
			artifactTrackerGetManifestHandler.ServeHTTP(w, r)
		case ArtifactTrackerDeleteAliasProcedure:
			artifactTrackerDeleteAliasHandler.ServeHTTP(w, r)
		case ArtifactTrackerReportInventoryProcedure:
			artifactTrackerReportInventoryHandler.ServeHTTP(w, r)
		case ArtifactTrackerApplyRetentionProcedure:
			artifactTrackerApplyRetentionHandler.ServeHTTP(w, r)
		case ArtifactTrackerListPeersProcedure:
			artifactTrackerListPeersHandler.ServeHTTP(w, r)
		case ArtifactTrackerSignalPeerProcedure:
			artifactTrackerSignalPeerHandler.ServeHTTP(w, r)
		case ArtifactTrackerReportTransferProcedure:
			artifactTrackerReportTransferHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactTrackerHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactTrackerHandler struct{}

func (UnimplementedArtifactTrackerHandler) PublishManifest(context.Context, *connect.Request[tinkerv1.PublishManifestRequest]) (*connect.Response[tinkerv1.PublishManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.PublishManifest is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) GetManifest(context.Context, *connect.Request[tinkerv1.GetManifestRequest]) (*connect.Response[tinkerv1.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.GetManifest is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) DeleteAlias(context.Context, *connect.Request[tinkerv1.DeleteAliasRequest]) (*connect.Response[tinkerv1.DeleteAliasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.DeleteAlias is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) ReportInventory(context.Context, *connect.Request[tinkerv1.ReportInventoryRequest]) (*connect.Response[tinkerv1.ReportInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.ReportInventory is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) ApplyRetention(context.Context, *connect.Request[tinkerv1.ApplyRetentionRequest]) (*connect.Response[tinkerv1.ApplyRetentionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.ApplyRetention is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) ListPeers(context.Context, *connect.Request[tinkerv1.ListPeersRequest]) (*connect.Response[tinkerv1.ListPeersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.ListPeers is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) SignalPeer(context.Context, *connect.BidiStream[tinkerv1.SignalMessage, tinkerv1.SignalMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.SignalPeer is not implemented"))
}

func (UnimplementedArtifactTrackerHandler) ReportTransfer(context.Context, *connect.Request[tinkerv1.ReportTransferRequest]) (*connect.Response[tinkerv1.ReportTransferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactTracker.ReportTransfer is not implemented"))
}

// ArtifactPeerClient is a client for the mlxgo.tinker.v1.ArtifactPeer service.
type ArtifactPeerClient interface {
	Have(context.Context, *connect.Request[tinkerv1.HaveRequest]) (*connect.Response[tinkerv1.HaveResponse], error)
	FetchChunk(context.Context, *connect.Request[tinkerv1.FetchChunkRequest]) (*connect.ServerStreamForClient[tinkerv1.ChunkFrame], error)
}

// NewArtifactPeerClient constructs a client for the mlxgo.tinker.v1.ArtifactPeer service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactPeerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactPeerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactPeerMethods := tinkerv1.File_mlxgo_tinker_v1_artifact_proto.Services().ByName("ArtifactPeer").Methods()
	return &artifactPeerClient{
		have: connect.NewClient[tinkerv1.HaveRequest, tinkerv1.HaveResponse](
			httpClient,
			baseURL+ArtifactPeerHaveProcedure,
			connect.WithSchema(artifactPeerMethods.ByName("Have")),
			connect.WithClientOptions(opts...),
		),
		fetchChunk: connect.NewClient[tinkerv1.FetchChunkRequest, tinkerv1.ChunkFrame](
			httpClient,
			baseURL+ArtifactPeerFetchChunkProcedure,
			connect.WithSchema(artifactPeerMethods.ByName("FetchChunk")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactPeerClient implements ArtifactPeerClient.
type artifactPeerClient struct {
	have       *connect.Client[tinkerv1.HaveRequest, tinkerv1.HaveResponse]
	fetchChunk *connect.Client[tinkerv1.FetchChunkRequest, tinkerv1.ChunkFrame]
}

// Have calls mlxgo.tinker.v1.ArtifactPeer.Have.
func (c *artifactPeerClient) Have(ctx context.Context, req *connect.Request[tinkerv1.HaveRequest]) (*connect.Response[tinkerv1.HaveResponse], error) {
	return c.have.CallUnary(ctx, req)
}

// FetchChunk calls mlxgo.tinker.v1.ArtifactPeer.FetchChunk.
func (c *artifactPeerClient) FetchChunk(ctx context.Context, req *connect.Request[tinkerv1.FetchChunkRequest]) (*connect.ServerStreamForClient[tinkerv1.ChunkFrame], error) {
	return c.fetchChunk.CallServerStream(ctx, req)
}

// ArtifactPeerHandler is an implementation of the mlxgo.tinker.v1.ArtifactPeer service.
type ArtifactPeerHandler interface {
	Have(context.Context, *connect.Request[tinkerv1.HaveRequest]) (*connect.Response[tinkerv1.HaveResponse], error)
	FetchChunk(context.Context, *connect.Request[tinkerv1.FetchChunkRequest], *connect.ServerStream[tinkerv1.ChunkFrame]) error
}

// NewArtifactPeerHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactPeerHandler(svc ArtifactPeerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactPeerMethods := tinkerv1.File_mlxgo_tinker_v1_artifact_proto.Services().ByName("ArtifactPeer").Methods()
	artifactPeerHaveHandler := connect.NewUnaryHandler(
		ArtifactPeerHaveProcedure,
		svc.Have,
		connect.WithSchema(artifactPeerMethods.ByName("Have")),
		connect.WithHandlerOptions(opts...),
	)
	artifactPeerFetchChunkHandler := connect.NewServerStreamHandler(
		ArtifactPeerFetchChunkProcedure,
		svc.FetchChunk,
		connect.WithSchema(artifactPeerMethods.ByName("FetchChunk")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mlxgo.tinker.v1.ArtifactPeer/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactPeerHaveProcedure:
			artifactPeerHaveHandler.ServeHTTP(w, r)
		case ArtifactPeerFetchChunkProcedure:
			artifactPeerFetchChunkHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactPeerHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactPeerHandler struct{}

func (UnimplementedArtifactPeerHandler) Have(context.Context, *connect.Request[tinkerv1.HaveRequest]) (*connect.Response[tinkerv1.HaveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactPeer.Have is not implemented"))
}

func (UnimplementedArtifactPeerHandler) FetchChunk(context.Context, *connect.Request[tinkerv1.FetchChunkRequest], *connect.ServerStream[tinkerv1.ChunkFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.ArtifactPeer.FetchChunk is not implemented"))
}
