// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mlxgo/tinker/v1/coordinator.proto

package tinkerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	tinkerv1 "github.com/tmc/localtinker/internal/tinkerproto/tinkerv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TinkerCoordinatorName is the fully-qualified name of the TinkerCoordinator service.
	TinkerCoordinatorName = "mlxgo.tinker.v1.TinkerCoordinator"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TinkerCoordinatorRegisterNodeProcedure is the fully-qualified name of the TinkerCoordinator's
	// RegisterNode RPC.
	TinkerCoordinatorRegisterNodeProcedure = "/mlxgo.tinker.v1.TinkerCoordinator/RegisterNode"
	// TinkerCoordinatorHeartbeatProcedure is the fully-qualified name of the TinkerCoordinator's
	// Heartbeat RPC.
	TinkerCoordinatorHeartbeatProcedure = "/mlxgo.tinker.v1.TinkerCoordinator/Heartbeat"
	// TinkerCoordinatorWatchProcedure is the fully-qualified name of the TinkerCoordinator's Watch RPC.
	TinkerCoordinatorWatchProcedure = "/mlxgo.tinker.v1.TinkerCoordinator/Watch"
	// TinkerCoordinatorReportProcedure is the fully-qualified name of the TinkerCoordinator's Report
	// RPC.
	TinkerCoordinatorReportProcedure = "/mlxgo.tinker.v1.TinkerCoordinator/Report"
)

// TinkerCoordinatorClient is a client for the mlxgo.tinker.v1.TinkerCoordinator service.
type TinkerCoordinatorClient interface {
	RegisterNode(context.Context, *connect.Request[tinkerv1.RegisterNodeRequest]) (*connect.Response[tinkerv1.RegisterNodeResponse], error)
	Heartbeat(context.Context, *connect.Request[tinkerv1.HeartbeatRequest]) (*connect.Response[tinkerv1.HeartbeatResponse], error)
	Watch(context.Context, *connect.Request[tinkerv1.WatchRequest]) (*connect.ServerStreamForClient[tinkerv1.NodeCommand], error)
	Report(context.Context) *connect.ClientStreamForClient[tinkerv1.NodeEvent, tinkerv1.ReportResponse]
}

// NewTinkerCoordinatorClient constructs a client for the mlxgo.tinker.v1.TinkerCoordinator service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTinkerCoordinatorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TinkerCoordinatorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tinkerCoordinatorMethods := tinkerv1.File_mlxgo_tinker_v1_coordinator_proto.Services().ByName("TinkerCoordinator").Methods()
	return &tinkerCoordinatorClient{
		registerNode: connect.NewClient[tinkerv1.RegisterNodeRequest, tinkerv1.RegisterNodeResponse](
			httpClient,
			baseURL+TinkerCoordinatorRegisterNodeProcedure,
			connect.WithSchema(tinkerCoordinatorMethods.ByName("RegisterNode")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[tinkerv1.HeartbeatRequest, tinkerv1.HeartbeatResponse](
			httpClient,
			baseURL+TinkerCoordinatorHeartbeatProcedure,
			connect.WithSchema(tinkerCoordinatorMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[tinkerv1.WatchRequest, tinkerv1.NodeCommand](
			httpClient,
			baseURL+TinkerCoordinatorWatchProcedure,
			connect.WithSchema(tinkerCoordinatorMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
		report: connect.NewClient[tinkerv1.NodeEvent, tinkerv1.ReportResponse](
			httpClient,
			baseURL+TinkerCoordinatorReportProcedure,
			connect.WithSchema(tinkerCoordinatorMethods.ByName("Report")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tinkerCoordinatorClient implements TinkerCoordinatorClient.
type tinkerCoordinatorClient struct {
	registerNode *connect.Client[tinkerv1.RegisterNodeRequest, tinkerv1.RegisterNodeResponse]
	heartbeat    *connect.Client[tinkerv1.HeartbeatRequest, tinkerv1.HeartbeatResponse]
	watch        *connect.Client[tinkerv1.WatchRequest, tinkerv1.NodeCommand]
	report       *connect.Client[tinkerv1.NodeEvent, tinkerv1.ReportResponse]
}

// RegisterNode calls mlxgo.tinker.v1.TinkerCoordinator.RegisterNode.
func (c *tinkerCoordinatorClient) RegisterNode(ctx context.Context, req *connect.Request[tinkerv1.RegisterNodeRequest]) (*connect.Response[tinkerv1.RegisterNodeResponse], error) {
	return c.registerNode.CallUnary(ctx, req)
}

// Heartbeat calls mlxgo.tinker.v1.TinkerCoordinator.Heartbeat.
func (c *tinkerCoordinatorClient) Heartbeat(ctx context.Context, req *connect.Request[tinkerv1.HeartbeatRequest]) (*connect.Response[tinkerv1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// Watch calls mlxgo.tinker.v1.TinkerCoordinator.Watch.
func (c *tinkerCoordinatorClient) Watch(ctx context.Context, req *connect.Request[tinkerv1.WatchRequest]) (*connect.ServerStreamForClient[tinkerv1.NodeCommand], error) {
	return c.watch.CallServerStream(ctx, req)
}

// Report calls mlxgo.tinker.v1.TinkerCoordinator.Report.
func (c *tinkerCoordinatorClient) Report(ctx context.Context) *connect.ClientStreamForClient[tinkerv1.NodeEvent, tinkerv1.ReportResponse] {
	return c.report.CallClientStream(ctx)
}

// TinkerCoordinatorHandler is an implementation of the mlxgo.tinker.v1.TinkerCoordinator service.
type TinkerCoordinatorHandler interface {
	RegisterNode(context.Context, *connect.Request[tinkerv1.RegisterNodeRequest]) (*connect.Response[tinkerv1.RegisterNodeResponse], error)
	Heartbeat(context.Context, *connect.Request[tinkerv1.HeartbeatRequest]) (*connect.Response[tinkerv1.HeartbeatResponse], error)
	Watch(context.Context, *connect.Request[tinkerv1.WatchRequest], *connect.ServerStream[tinkerv1.NodeCommand]) error
	Report(context.Context, *connect.ClientStream[tinkerv1.NodeEvent]) (*connect.Response[tinkerv1.ReportResponse], error)
}

// NewTinkerCoordinatorHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTinkerCoordinatorHandler(svc TinkerCoordinatorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tinkerCoordinatorMethods := tinkerv1.File_mlxgo_tinker_v1_coordinator_proto.Services().ByName("TinkerCoordinator").Methods()
	tinkerCoordinatorRegisterNodeHandler := connect.NewUnaryHandler(
		TinkerCoordinatorRegisterNodeProcedure,
		svc.RegisterNode,
		connect.WithSchema(tinkerCoordinatorMethods.ByName("RegisterNode")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerCoordinatorHeartbeatHandler := connect.NewUnaryHandler(
		TinkerCoordinatorHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(tinkerCoordinatorMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerCoordinatorWatchHandler := connect.NewServerStreamHandler(
		TinkerCoordinatorWatchProcedure,
		svc.Watch,
		connect.WithSchema(tinkerCoordinatorMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerCoordinatorReportHandler := connect.NewClientStreamHandler(
		TinkerCoordinatorReportProcedure,
		svc.Report,
		connect.WithSchema(tinkerCoordinatorMethods.ByName("Report")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mlxgo.tinker.v1.TinkerCoordinator/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TinkerCoordinatorRegisterNodeProcedure:
			tinkerCoordinatorRegisterNodeHandler.ServeHTTP(w, r)
		case TinkerCoordinatorHeartbeatProcedure:
			tinkerCoordinatorHeartbeatHandler.ServeHTTP(w, r)
		case TinkerCoordinatorWatchProcedure:
			tinkerCoordinatorWatchHandler.ServeHTTP(w, r)
		case TinkerCoordinatorReportProcedure:
			tinkerCoordinatorReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTinkerCoordinatorHandler returns CodeUnimplemented from all methods.
type UnimplementedTinkerCoordinatorHandler struct{}

func (UnimplementedTinkerCoordinatorHandler) RegisterNode(context.Context, *connect.Request[tinkerv1.RegisterNodeRequest]) (*connect.Response[tinkerv1.RegisterNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerCoordinator.RegisterNode is not implemented"))
}

func (UnimplementedTinkerCoordinatorHandler) Heartbeat(context.Context, *connect.Request[tinkerv1.HeartbeatRequest]) (*connect.Response[tinkerv1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerCoordinator.Heartbeat is not implemented"))
}

func (UnimplementedTinkerCoordinatorHandler) Watch(context.Context, *connect.Request[tinkerv1.WatchRequest], *connect.ServerStream[tinkerv1.NodeCommand]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerCoordinator.Watch is not implemented"))
}

func (UnimplementedTinkerCoordinatorHandler) Report(context.Context, *connect.ClientStream[tinkerv1.NodeEvent]) (*connect.Response[tinkerv1.ReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerCoordinator.Report is not implemented"))
}
