// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mlxgo/tinker/v1/node.proto

package tinkerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	tinkerv1 "github.com/tmc/localtinker/internal/tinkerproto/tinkerv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TinkerNodeName is the fully-qualified name of the TinkerNode service.
	TinkerNodeName = "mlxgo.tinker.v1.TinkerNode"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TinkerNodeRunProcedure is the fully-qualified name of the TinkerNode's Run RPC.
	TinkerNodeRunProcedure = "/mlxgo.tinker.v1.TinkerNode/Run"
	// TinkerNodeCancelProcedure is the fully-qualified name of the TinkerNode's Cancel RPC.
	TinkerNodeCancelProcedure = "/mlxgo.tinker.v1.TinkerNode/Cancel"
	// TinkerNodeDrainProcedure is the fully-qualified name of the TinkerNode's Drain RPC.
	TinkerNodeDrainProcedure = "/mlxgo.tinker.v1.TinkerNode/Drain"
	// TinkerNodeHealthProcedure is the fully-qualified name of the TinkerNode's Health RPC.
	TinkerNodeHealthProcedure = "/mlxgo.tinker.v1.TinkerNode/Health"
)

// TinkerNodeClient is a client for the mlxgo.tinker.v1.TinkerNode service.
type TinkerNodeClient interface {
	Run(context.Context, *connect.Request[tinkerv1.NodeCommand]) (*connect.Response[tinkerv1.OperationResult], error)
	Cancel(context.Context, *connect.Request[tinkerv1.CancelRequest]) (*connect.Response[tinkerv1.CancelResponse], error)
	Drain(context.Context, *connect.Request[tinkerv1.DrainRequest]) (*connect.Response[tinkerv1.DrainResponse], error)
	Health(context.Context, *connect.Request[tinkerv1.NodeHealthRequest]) (*connect.Response[tinkerv1.NodeHealthResponse], error)
}

// NewTinkerNodeClient constructs a client for the mlxgo.tinker.v1.TinkerNode service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTinkerNodeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TinkerNodeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tinkerNodeMethods := tinkerv1.File_mlxgo_tinker_v1_node_proto.Services().ByName("TinkerNode").Methods()
	return &tinkerNodeClient{
		run: connect.NewClient[tinkerv1.NodeCommand, tinkerv1.OperationResult](
			httpClient,
			baseURL+TinkerNodeRunProcedure,
			connect.WithSchema(tinkerNodeMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
		cancel: connect.NewClient[tinkerv1.CancelRequest, tinkerv1.CancelResponse](
			httpClient,
			baseURL+TinkerNodeCancelProcedure,
			connect.WithSchema(tinkerNodeMethods.ByName("Cancel")),
			connect.WithClientOptions(opts...),
		),
		drain: connect.NewClient[tinkerv1.DrainRequest, tinkerv1.DrainResponse](
			httpClient,
			baseURL+TinkerNodeDrainProcedure,
			connect.WithSchema(tinkerNodeMethods.ByName("Drain")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[tinkerv1.NodeHealthRequest, tinkerv1.NodeHealthResponse](
			httpClient,
			baseURL+TinkerNodeHealthProcedure,
			connect.WithSchema(tinkerNodeMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tinkerNodeClient implements TinkerNodeClient.
type tinkerNodeClient struct {
	run    *connect.Client[tinkerv1.NodeCommand, tinkerv1.OperationResult]
	cancel *connect.Client[tinkerv1.CancelRequest, tinkerv1.CancelResponse]
	drain  *connect.Client[tinkerv1.DrainRequest, tinkerv1.DrainResponse]
	health *connect.Client[tinkerv1.NodeHealthRequest, tinkerv1.NodeHealthResponse]
}

// Run calls mlxgo.tinker.v1.TinkerNode.Run.
func (c *tinkerNodeClient) Run(ctx context.Context, req *connect.Request[tinkerv1.NodeCommand]) (*connect.Response[tinkerv1.OperationResult], error) {
	return c.run.CallUnary(ctx, req)
}

// Cancel calls mlxgo.tinker.v1.TinkerNode.Cancel.
func (c *tinkerNodeClient) Cancel(ctx context.Context, req *connect.Request[tinkerv1.CancelRequest]) (*connect.Response[tinkerv1.CancelResponse], error) {
	return c.cancel.CallUnary(ctx, req)
}

// Drain calls mlxgo.tinker.v1.TinkerNode.Drain.
func (c *tinkerNodeClient) Drain(ctx context.Context, req *connect.Request[tinkerv1.DrainRequest]) (*connect.Response[tinkerv1.DrainResponse], error) {
	return c.drain.CallUnary(ctx, req)
}

// Health calls mlxgo.tinker.v1.TinkerNode.Health.
func (c *tinkerNodeClient) Health(ctx context.Context, req *connect.Request[tinkerv1.NodeHealthRequest]) (*connect.Response[tinkerv1.NodeHealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// TinkerNodeHandler is an implementation of the mlxgo.tinker.v1.TinkerNode service.
type TinkerNodeHandler interface {
	Run(context.Context, *connect.Request[tinkerv1.NodeCommand]) (*connect.Response[tinkerv1.OperationResult], error)
	Cancel(context.Context, *connect.Request[tinkerv1.CancelRequest]) (*connect.Response[tinkerv1.CancelResponse], error)
	Drain(context.Context, *connect.Request[tinkerv1.DrainRequest]) (*connect.Response[tinkerv1.DrainResponse], error)
	Health(context.Context, *connect.Request[tinkerv1.NodeHealthRequest]) (*connect.Response[tinkerv1.NodeHealthResponse], error)
}

// NewTinkerNodeHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTinkerNodeHandler(svc TinkerNodeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tinkerNodeMethods := tinkerv1.File_mlxgo_tinker_v1_node_proto.Services().ByName("TinkerNode").Methods()
	tinkerNodeRunHandler := connect.NewUnaryHandler(
		TinkerNodeRunProcedure,
		svc.Run,
		connect.WithSchema(tinkerNodeMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerNodeCancelHandler := connect.NewUnaryHandler(
		TinkerNodeCancelProcedure,
		svc.Cancel,
		connect.WithSchema(tinkerNodeMethods.ByName("Cancel")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerNodeDrainHandler := connect.NewUnaryHandler(
		TinkerNodeDrainProcedure,
		svc.Drain,
		connect.WithSchema(tinkerNodeMethods.ByName("Drain")),
		connect.WithHandlerOptions(opts...),
	)
	tinkerNodeHealthHandler := connect.NewUnaryHandler(
		TinkerNodeHealthProcedure,
		svc.Health,
		connect.WithSchema(tinkerNodeMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mlxgo.tinker.v1.TinkerNode/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TinkerNodeRunProcedure:
			tinkerNodeRunHandler.ServeHTTP(w, r)
		case TinkerNodeCancelProcedure:
			tinkerNodeCancelHandler.ServeHTTP(w, r)
		case TinkerNodeDrainProcedure:
			tinkerNodeDrainHandler.ServeHTTP(w, r)
		case TinkerNodeHealthProcedure:
			tinkerNodeHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTinkerNodeHandler returns CodeUnimplemented from all methods.
type UnimplementedTinkerNodeHandler struct{}

func (UnimplementedTinkerNodeHandler) Run(context.Context, *connect.Request[tinkerv1.NodeCommand]) (*connect.Response[tinkerv1.OperationResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerNode.Run is not implemented"))
}

func (UnimplementedTinkerNodeHandler) Cancel(context.Context, *connect.Request[tinkerv1.CancelRequest]) (*connect.Response[tinkerv1.CancelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerNode.Cancel is not implemented"))
}

func (UnimplementedTinkerNodeHandler) Drain(context.Context, *connect.Request[tinkerv1.DrainRequest]) (*connect.Response[tinkerv1.DrainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerNode.Drain is not implemented"))
}

func (UnimplementedTinkerNodeHandler) Health(context.Context, *connect.Request[tinkerv1.NodeHealthRequest]) (*connect.Response[tinkerv1.NodeHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mlxgo.tinker.v1.TinkerNode.Health is not implemented"))
}
